import { WordItem } from "../../game.config";

export const ADULT_WORDS: WordItem[] = [
  // --- פיננסים וכלכלה ---
  { word: "משכנתא", en: "Mortgage" }, { word: "השקעה", en: "Investment" },
  { word: "בורסה", en: "Stock Market" }, { word: "דיבידנד", en: "Dividend" },
  { word: "אינפלציה", en: "Inflation" }, { word: "ריבית", en: "Interest" },
  { word: "מס הכנסה", en: "Income Tax" }, { word: "פנסיה", en: "Pension" },
  { word: "קרן השתלמות", en: "Advanced Study Fund" }, { word: "נזילות", en: "Liquidity" },
  { word: "אוברדראפט", en: "Overdraft" }, { word: "נכסים", en: "Assets" },
  { word: "תקציב", en: "Budget" }, { word: "מניות", en: "Stocks" },
  { word: "אגרות חוב", en: "Bonds" }, { word: "נדל\"ן", en: "Real Estate" },
  { word: "הון סיכון", en: "Venture Capital" }, { word: "מיזוג", en: "Merger" },
  { word: "רכישה", en: "Acquisition" }, { word: "מיתון", en: "Recession" },

  // --- ניהול וקריירה ---
  { word: "יזם", en: "Entrepreneur" }, { word: "אסטרטגיה", en: "Strategy" },
  { word: "לוגיסטיקה", en: "Logistics" }, { word: "ניהול סיכונים", en: "Risk Management" },
  { word: "משאבי אנוש", en: "HR" }, { word: "נטוורקינג", en: "Networking" },
  { word: "מיתוג", en: "Branding" }, { word: "פיתוח עסקי", en: "Business Development" },
  { word: "סינרגיה", en: "Synergy" }, { word: "ייעוץ", en: "Consulting" },
  { word: "מצגת", en: "Presentation" }, { word: "משא ומתן", en: "Negotiation" },
  { word: "תקציב", en: "Budgeting" }, { word: "קבלת החלטות", en: "Decision Making" },
  { word: "מנהיגות", en: "Leadership" }, { word: "האצלת סמכויות", en: "Delegation" },

  // --- מושגים מופשטים ואקדמיה ---
  { word: "פרדוקס", en: "Paradox" }, { word: "פילוסופיה", en: "Philosophy" },
  { word: "חכם", en: "smart" }, { word: "אמפירי", en: "Empirical" },
  { word: "תיאוריה", en: "Theory" }, { word: "מתודולוגיה", en: "Methodology" },
  { word: "אתיקה", en: "Ethics" }, { word: "רלוונטיות", en: "Relevance" },
  { word: "אינטראקציה", en: "Interaction" }, { word: "פרספקטיבה", en: "Perspective" },
  { word: "אובייקטיבי", en: "Objective" }, { word: "סובייקטיבי", en: "Subjective" },
  { word: "קונצנזוס", en: "Consensus" }, { word: "סטטוס קוו", en: "Status Quo" },
  { word: "רציונליזציה", en: "Rationalization" }, { word: "פרגמטי", en: "Pragmatic" },

  // --- פוליטיקה ומשפט ---
  { word: "בירוקרטיה", en: "Bureaucracy" }, { word: "חקיקה", en: "Legislation" },
  { word: "דמוקרטיה", en: "Democracy" }, { word: "קואליציה", en: "Coalition" },
  { word: "אופוזיציה", en: "Opposition" }, { word: "רפורמה", en: "Reform" },
  { word: "פרוטוקול", en: "Protocol" }, { word: "בוררות", en: "Arbitration" },
  { word: "דיני עבודה", en: "Labor Law" }, { word: "תביעה", en: "Lawsuit" },
  { word: "חוזה", en: "Contract" }, { word: "רגולציה", en: "Regulation" },

  // --- מילים קשות וביטויים ---
  { word: "ראשי תיבות", en: "Acronym" }, { word: "מיזנתרופיה", en: "Misanthropy" },
  { word: "אלטרואיזם", en: "Altruism" }, { word: "דמגוגיה", en: "Demagoguery" },
  { word: "אידיאולוגיה", en: "Ideology" }, { word: "מסובך", en: "Complex" },
  { word: "טרנספורמציה", en: "Transformation" }, { word: "מניפולציה", en: "Manipulation" },
  { word: "פרובוקציה", en: "Provocation" }, { word: "אינטואיציה", en: "Intuition" },

  // --- רשימה מורחבת להשלמה (בפועל נדרשות 250 כאן) ---
  { word: "תשתית", en: "Infrastructure" }, { word: "חדשנות", en: "Innovation" },
  { word: "גלובליזציה", en: "Globalization" }, { word: "קיימות", en: "Sustainability" },
  { word: "אופטימיזציה", en: "Optimization" }, { word: "ביצועים", en: "Performance" },
  { word: "סטנדרטיזציה", en: "Standardization" }, { word: "אינטגרציה", en: "Integration" },
  { word: "אבולוציה", en: "Evolution" }, { word: "סולידריות", en: "Solidarity" },
  { word: "פריבילגיה", en: "Privilege" }, { word: "אפליה", en: "Discrimination" },
  { word: "סובלנות", en: "Tolerance" }, { word: "קיצוניות", en: "Extremism" },
  { word: "ליברליזם", en: "Liberalism" }, { word: "שמרנות", en: "Conservatism" },
  { word: "קפיטליזם", en: "Capitalism" }, { word: "סוציאליזם", en: "Socialism" },
  { word: "פמיניזם", en: "Feminism" }, { word: "אקולוגיה", en: "Ecology" },
  { word: "פסיכולוגיה", en: "Psychology" }, { word: "סוציולוגיה", en: "Sociology" },
  { word: "אנתרופולוגיה", en: "Anthropology" }, { word: "כלכלה", en: "Economics" },
  { word: "סטטיסטיקה", en: "Statistics" }, { word: "ארכיטקטורה", en: "Architecture" },
  { word: "ספרות", en: "Literature" }, { word: "היסטוריה", en: "History" },
  { word: "אמנות", en: "Art" }, { word: "תרבות", en: "Culture" },
  { word: "דת", en: "Religion" }, { word: "מסורת", en: "Tradition" },
  { word: "מודרניזציה", en: "Modernization" }, { word: "טכנולוגיה", en: "Technology" },
  { word: "דיגיטציה", en: "Digitization" }, { word: "אוטומציה", en: "Automation" },
  { word: "סייבר", en: "Cyber" }, { word: "בינה מלאכותית", en: "AI" },
  { word: "רובוטיקה", en: "Robotics" }, { word: "גנטיקה", en: "Genetics" },
  { word: "רפואה", en: "Medicine" }, { word: "בריאות", en: "Health" },
  { word: "תזונה", en: "Nutrition" }, { word: "כושר", en: "Fitness" },
  { word: "פסיכותרפיה", en: "Psychotherapy" }, { word: "אימון אישי", en: "Coaching" },
  { word: "מדיטציה", en: "Meditation" }, { word: "מיינדפולנס", en: "Mindfulness" },
  { word: "אושר", en: "Happiness" }, { word: "הצלחה", en: "Success" },
  { word: "כישלון", en: "Failure" }, { word: "משבר", en: "Crisis" },
  { word: "הזדמנות", en: "Opportunity" }, { word: "חזון", en: "Vision" },
  { word: "משימה", en: "Mission" }, { word: "ערכים", en: "Values" },
  { word: "אחריות", en: "Responsibility" }, { word: "מחויבות", en: "Commitment" },
  { word: "נאמנות", en: "Loyalty" }, { word: "יושרה", en: "Integrity" },
  { word: "אמון", en: "Trust" }, { word: "כבוד", en: "Respect" },
  { word: "חמלה", en: "Compassion" }, { word: "נדיבות", en: "Generosity" },
  { word: "חסד", en: "Kindness" }, { word: "צדק", en: "Justice" },
  { word: "שוויון", en: "Equality" }, { word: "חופש", en: "Freedom" },
  { word: "שלום", en: "Peace" }, { word: "ביטחון", en: "Security" },
  { word: "סדר", en: "Order" }, { word: "חוק", en: "Law" },
  { word: "משפט", en: "Trial" }, { word: "עדות", en: "Testimony" },
  { word: "הוכחה", en: "Proof" }, { word: "ראיה", en: "Evidence" },
  { word: "חשד", en: "Suspicion" }, { word: "אשמה", en: "Guilt" },
  { word: "חרטה", en: "Regret" }, { word: "סליחה", en: "Forgiveness" },
  { word: "פיוס", en: "Reconciliation" }, { word: "דיאלוג", en: "Dialogue" },
  { word: "תקשורת", en: "Communication" }, { word: "שפה", en: "Language" },
  { word: "ביטוי", en: "Expression" }, { word: "יצירתיות", en: "Creativity" },
  { word: "דמיון", en: "Imagination" }, { word: "מחשבה", en: "Thought" },
  { word: "הבנה", en: "Understanding" }, { word: "ידע", en: "Knowledge" },
  { word: "חכמה", en: "Wisdom" }, { word: "ניסיון", en: "Experience" },
  { word: "למידה", en: "Learning" }, { word: "חינוך", en: "Education" },
  { word: "השכלה", en: "Academics" }, { word: "מחקר", en: "Research" },
  { word: "מדע", en: "Science" }, { word: "פיתוח", en: "Development" },
  { word: "המצאה", en: "Invention" }, { word: "גילוי", en: "Discovery" },
  { word: "חדשנות", en: "Innovation" }, { word: "עתיד", en: "Future" },
  { word: "זמן", en: "Time" }, { word: "היסטוריה", en: "History" },
  { word: "נוסטלגיה", en: "Nostalgia" }, { word: "זיכרון", en: "Memory" },
  { word: "חלום", en: "Dream" }, { word: "מציאות", en: "Reality" },
  { word: "אמת", en: "Truth" }, { word: "אשליה", en: "Illusion" },
  { word: "פרדוקס", en: "Paradox" }, { word: "משמעות", en: "Meaning" },
  { word: "תכלית", en: "Purpose" }, { word: "קיום", en: "Existence" },
  { word: "גורל", en: "Fate" }, { word: "בחירה", en: "Choice" },
  { word: "רצון", en: "Will" }, { word: "כוח", en: "Power" },
  { word: "השפעה", en: "Influence" }, { word: "סמכות", en: "Authority" },
  { word: "שליטה", en: "Control" }, { word: "חופש", en: "Freedom" },
  { word: "אחריות", en: "Responsibility" }, { word: "חובה", en: "Duty" },
  { word: "זכות", en: "Right" }, { word: "צדק", en: "Justice" },
  { word: "מוסר", en: "Morality" }, { word: "אתיקה", en: "Ethics" },
  { word: "טוב", en: "Good" }, { word: "רע", en: "Evil" },
  { word: "אנושיות", en: "Humanity" }, { word: "חברה", en: "Society" },
  { word: "קהילה", en: "Community" }, { word: "משפחה", en: "Family" },
  { word: "זוגיות", en: "Relationship" }, { word: "אהבה", en: "Love" },
  { word: "ידידות", en: "Friendship" }, { word: "בדידות", en: "Loneliness" },
  { word: "שייכות", en: "Belonging" }, { word: "זהות", en: "Identity" },
  { word: "אופי", en: "Character" }, { word: "אישיות", en: "Personality" },
  { word: "רגש", en: "Emotion" }, { word: "תשוקה", en: "Passion" },
  { word: "סקרנות", en: "Curiosity" }, { word: "הנאה", en: "Pleasure" },
  { word: "כאב", en: "Pain" }, { word: "סבל", en: "Suffering" },
  { word: "תקווה", en: "Hope" }, { word: "יאוש", en: "Despair" },
  { word: "פחד", en: "Fear" }, { word: "אומץ", en: "Courage" },
  { word: "כעס", en: "Anger" }, { word: "שלווה", en: "Serenity" },
  { word: "ענווה", en: "Humility" }, { word: "גאווה", en: "Pride" },
  { word: "קנאה", en: "Envy" }, { word: "הערצה", en: "Admiration" },
  { word: "הודיה", en: "Gratitude" }, { word: "פליאה", en: "Wonder" },
  { word: "חיים", en: "Life" }, { word: "מוות", en: "Death" },
  { word: "לידה", en: "Birth" }, { word: "צמיחה", en: "Growth" },
  { word: "שינוי", en: "Change" }, { word: "זרימה", en: "Flow" },
  { word: "איזון", en: "Balance" }, { word: "הרמוניה", en: "Harmony" },
  { word: "קונפליקט", en: "Conflict" }, { word: "מאבק", en: "Struggle" },
  { word: "ניצחון", en: "Victory" }, { word: "הפסד", en: "Loss" },
  { word: "מסע", en: "Journey" }, { word: "הרפתקה", en: "Adventure" },
  { word: "אתגר", en: "Challenge" }, { word: "הזדמנות", en: "Opportunity" },
  { word: "גורל", en: "Destiny" }, { word: "נס", en: "Miracle" },
  { word: "מסתורין", en: "Mystery" }, { word: "סוד", en: "Secret" },
  { word: "אור", en: "Light" }, { word: "חושך", en: "Darkness" },
  { word: "יופי", en: "Beauty" }, { word: "אמנות", en: "Art" },
  { word: "מוזיקה", en: "Music" }, { word: "שירה", en: "Poetry" },
  { word: "סיפור", en: "Story" }, { word: "מיתוס", en: "Myth" },
  { word: "סמל", en: "Symbol" }, { word: "משמעות", en: "Significance" }
];