export const CELEBS_WORDS = [
    // --- 1. זמרים וזמרות (singer) ---
    { word: "שלמה ארצי", en: "Shlomo Artzi", category: "singer" },
    { word: "אייל גולן", en: "Eyal Golan", category: "singer" },
    { word: "נועה קירל", en: "Noa Kirel", category: "singer" },
    { word: "עומר אדם", en: "Omer Adam", category: "singer" },
    { word: "אריק איינשטיין", en: "Arik Einstein", category: "singer" },
    { word: "ביונסה", en: "Beyonce", category: "singer" },
    { word: "מייקל ג'קסון", en: "Michael Jackson", category: "singer" },
    { word: "מדונה", en: "Madonna", category: "singer" },
    { word: "טיילור סוויפט", en: "Taylor Swift", category: "singer" },
    { word: "אדל", en: "Adele", category: "singer" },
    { word: "חנן בן ארי", en: "Hanan Ben Ari", category: "singer" },
    { word: "עדן חסון", en: "Eden Hason", category: "singer" },
    { word: "ברי סחרוף", en: "Berry Sakharof", category: "singer" },
    { word: "זהר ארגוב", en: "Zohar Argov", category: "singer" },
    { word: "עדן בן זקן", en: "Eden Ben Zaken", category: "singer" },
    { word: "סטטיק", en: "Static", category: "singer" },
    { word: "בן אל תבורי", en: "Ben El Tavori", category: "singer" },
    { word: "מרגי", en: "Mergi", category: "singer" },
    { word: "ריטה", en: "Rita", category: "singer" },
    { word: "רמי קלינשטיין", en: "Rami Kleinstein", category: "singer" },
    { word: "אביב גפן", en: "Aviv Geffen", category: "singer" },
    { word: "נינט טייב", en: "Ninet Tayeb", category: "singer" },
    { word: "עידן רייכל", en: "Idan Raichel", category: "singer" },
    { word: "עברי לידר", en: "Ivri Lider", category: "singer" },
    { word: "ריקי גל", en: "Riki Gal", category: "singer" },
    { word: "יהודית רביץ", en: "Yehudit Ravitz", category: "singer" },
    { word: "גידי גוב", en: "Gidi Gov", category: "singer" },
    { word: "דני סנדרסון", en: "Danny Sanderson", category: "singer" },
    { word: "חוה אלברשטיין", en: "Chava Alberstein", category: "singer" },
    { word: "ירדנה ארזי", en: "Yardena Arazi", category: "singer" },
    { word: "עפרה חזה", en: "Ofra Haza", category: "singer" },
    { word: "זהבה בן", en: "Zehava Ben", category: "singer" },
    { word: "שרית חדד", en: "Sarit Hadad", category: "singer" },
    { word: "משה פרץ", en: "Moshe Peretz", category: "singer" },
    { word: "דודו אהרון", en: "Dudu Aharon", category: "singer" },
    { word: "ליאור נרקיס", en: "Lior Narkis", category: "singer" },
    { word: "קובי פרץ", en: "Kobi Peretz", category: "singer" },
    { word: "איתי לוי", en: "Itay Levi", category: "singer" },
    { word: "אושר כהן", en: "Osher Cohen", category: "singer" },
    { word: "ששון איפרם שאולוב", en: "Sasson Shaulov", category: "singer" },
    { word: "יסמין מועלם", en: "Jasmin Moallem", category: "singer" },
    { word: "נגה ארז", en: "Noga Erez", category: "singer" },
    { word: "אנה זק", en: "Anna Zak", category: "singer" },
    { word: "רן דנקר", en: "Ran Danker", category: "singer" },
    { word: "הראל סקעת", en: "Harel Skaat", category: "singer" },
    { word: "שירי מימון", en: "Shiri Maimon", category: "singer" },
    { word: "מארינה מקסימיליאן", en: "Marina Maximilian", category: "singer" },
    { word: "יובל דיין", en: "Yuval Dayan", category: "singer" },
    { word: "נתן גושן", en: "Natan Goshen", category: "singer" },
    { word: "אליעד נחום", en: "Eliad", category: "singer" },
    { word: "אברהם טל", en: "Avraham Tal", category: "singer" },
    { word: "מוש בן ארי", en: "Mosh Ben Ari", category: "singer" },
    { word: "מוקי", en: "Muki", category: "singer" },
    { word: "ג'סטין ביבר", en: "Justin Bieber", category: "singer" },
    { word: "אריאנה גרנדה", en: "Ariana Grande", category: "singer" },
    { word: "ריהאנה", en: "Rihanna", category: "singer" },
    { word: "דרייק", en: "Drake", category: "singer" },
    { word: "קניה ווסט", en: "Kanye West", category: "singer" },
    { word: "אמינם", en: "Eminem", category: "singer" },
    { word: "ליידי גאגא", en: "Lady Gaga", category: "singer" },
    { word: "ברונו מארס", en: "Bruno Mars", category: "singer" },
    { word: "בילי אייליש", en: "Billie Eilish", category: "singer" },
    { word: "פרדי מרקורי", en: "Freddie Mercury", category: "singer" },
    { word: "אלביס פרסלי", en: "Elvis Presley", category: "singer" },
    { word: "מייקל בובלה", en: "Michael Buble", category: "singer" },
    { word: "פרנק סינטרה", en: "Frank Sinatra", category: "singer" },
    { word: "בוב מארלי", en: "Bob Marley", category: "singer" },
    { word: "ג'ון לנון", en: "John Lennon", category: "singer" },
    { word: "פול מקרטני", en: "Paul McCartney", category: "singer" },
    { word: "מיק ג'אגר", en: "Mick Jagger", category: "singer" },
    { word: "דיוויד בואי", en: "David Bowie", category: "singer" },
    { word: "אלטון ג'ון", en: "Elton John", category: "singer" },
    { word: "סטיבי וונדר", en: "Stevie Wonder", category: "singer" },
    { word: "מייקל סטייפ", en: "Michael Stipe", category: "singer" },
    { word: "בונו", en: "Bono", category: "singer" },
    { word: "אקסל רוז", en: "Axl Rose", category: "singer" },
    { word: "קורט קוביין", en: "Kurt Cobain", category: "singer" },
    { word: "איימי ויינהאוס", en: "Amy Winehouse", category: "singer" },
    { word: "וויטני יוסטון", en: "Whitney Houston", category: "singer" },
    { word: "סלין דיון", en: "Celine Dion", category: "singer" },
    { word: "מריה קארי", en: "Mariah Carey", category: "singer" },
    { word: "ג'ניפר לופז", en: "Jennifer Lopez", category: "singer" },
    { word: "שאקירה", en: "Shakira", category: "singer" },
    { word: "בריטני ספירס", en: "Britney Spears", category: "singer" },
    { word: "כריסטינה אגילרה", en: "Christina Aguilera", category: "singer" },
    { word: "פינק", en: "Pink", category: "singer" },
    { word: "קייטי פרי", en: "Katy Perry", category: "singer" },
  
    // --- 2. שחקנים ושחקניות (actor) ---
    { word: "גל גדות", en: "Gal Gadot", category: "actor" },
    { word: "בראד פיט", en: "Brad Pitt", category: "actor" },
    { word: "לאונרדו דיקפריו", en: "Leonardo DiCaprio", category: "actor" },
    { word: "מריל סטריפ", en: "Meryl Streep", category: "actor" },
    { word: "איילת זורר", en: "Ayelet Zurer", category: "actor" },
    { word: "טום קרוז", en: "Tom Cruise", category: "actor" },
    { word: "ג'וני דפ", en: "Johnny Depp", category: "actor" },
    { word: "אנג'לינה ג'ולי", en: "Angelina Jolie", category: "actor" },
    { word: "ג'ניפר אניסטון", en: "Jennifer Aniston", category: "actor" },
    { word: "ויל סמית'", en: "Will Smith", category: "actor" },
    { word: "מורגן פרימן", en: "Morgan Freeman", category: "actor" },
    { word: "רוברט דה נירו", en: "Robert De Niro", category: "actor" },
    { word: "אל פצ'ינו", en: "Al Pacino", category: "actor" },
    { word: "טום הנקס", en: "Tom Hanks", category: "actor" },
    { word: "ג'וליה רוברטס", en: "Julia Roberts", category: "actor" },
    { word: "סקרלט ג'והנסון", en: "Scarlett Johansson", category: "actor" },
    { word: "דוויין ג'ונסון", en: "Dwayne Johnson", category: "actor" },
    { word: "מרגו רובי", en: "Margot Robbie", category: "actor" },
    { word: "ראיין גוסלינג", en: "Ryan Gosling", category: "actor" },
    { word: "אמה סטון", en: "Emma Stone", category: "actor" },
    { word: "נטלי פורטמן", en: "Natalie Portman", category: "actor" },
    { word: "שירה האס", en: "Shira Haas", category: "actor" },
    { word: "ליאור אשכנזי", en: "Lior Ashkenazi", category: "actor" },
    { word: "יהודה לוי", en: "Yehuda Levi", category: "actor" },
    { word: "אביב אלוש", en: "Aviv Alush", category: "actor" },
    { word: "נועה תשבי", en: "Noa Tishby", category: "actor" },
    { word: "אדווה דדון", en: "Adva Dadon", category: "actor" },
    { word: "צחי הלוי", en: "Tsahi Halevi", category: "actor" },
    { word: "איתי טיראן", en: "Itay Tiran", category: "actor" },
    { word: "אסי כהן", en: "Assi Cohen", category: "actor" },
    { word: "שלום מיכאלשווילי", en: "Shalom Michaelshwilli", category: "actor" },
    { word: "ציון ברוך", en: "Zion Baruch", category: "actor" },
    { word: "אסי ישראלוף", en: "Assi Israelof", category: "actor" },
    { word: "עדי אשכנזי", en: "Adi Ashkenazi", category: "actor" },
    { word: "רותם סלע", en: "Rotem Sela", category: "actor" },
    { word: "אסי עזר", en: "Assi Azar", category: "actor" },
    { word: "גיא זוארץ", en: "Guy Zu-Aretz", category: "actor" },
    { word: "ליאור רז", en: "Lior Raz", category: "actor" },
    { word: "מיכאל אלוני", en: "Michael Aloni", category: "actor" },
    { word: "עוז זהבי", en: "Oz Zehavi", category: "actor" },
  
    // --- 3. כדורגלנים (footballer) ---
    { word: "ליאו מסי", en: "Lionel Messi", category: "footballer" },
    { word: "כריסטיאנו רונאלדו", en: "Cristiano Ronaldo", category: "footballer" },
    { word: "קיליאן אמבפה", en: "Kylian Mbappe", category: "footballer" },
    { word: "ארלינג הולאנד", en: "Erling Haaland", category: "footballer" },
    { word: "ערן זהבי", en: "Eran Zahavi", category: "footballer" },
    { word: "מנור סולומון", en: "Manor Solomon", category: "footballer" },
    { word: "יוסי בניון", en: "Yossi Benayoun", category: "footballer" },
    { word: "אלי אוחנה", en: "Eli Ohana", category: "footballer" },
    { word: "אורי מלמיליאן", en: "Uri Malmilian", category: "footballer" },
    { word: "דייוויד בקהאם", en: "David Beckham", category: "footballer" },
    { word: "זינדין זידאן", en: "Zinedine Zidane", category: "footballer" },
    { word: "רונאלדיניו", en: "Ronaldinho", category: "footballer" },
    { word: "פלה", en: "Pele", category: "footballer" },
    { word: "דייגו מראדונה", en: "Diego Maradona", category: "footballer" },
    { word: "ניימאר", en: "Neymar", category: "footballer" },
    { word: "מוחמד סלאח", en: "Mohamed Salah", category: "footballer" },
    { word: "הארי קיין", en: "Harry Kane", category: "footballer" },
    { word: "לואיס סוארס", en: "Luis Suarez", category: "footballer" },
    { word: "קארים בנזמה", en: "Karim Benzema", category: "footballer" },
    { word: "לוקה מודריץ'", en: "Luka Modric", category: "footballer" },
    { word: "רוברט לבנדובסקי", en: "Robert Lewandowski", category: "footballer" },
    { word: "זלאטן איברהימוביץ'", en: "Zlatan Ibrahimovic", category: "footballer" },
    { word: "דניאל פרץ", en: "Daniel Peretz", category: "footballer" },
    { word: "אוסקר גלוך", en: "Oscar Gloukh", category: "footballer" },
  
    // --- 4. פוליטיקאים וראשי מדינה (head_of_state / politician) ---
    { word: "בנימין נתניהו", en: "Benjamin Netanyahu", category: "head_of_state" },
    { word: "יצחק רבין", en: "Yitzhak Rabin", category: "head_of_state" },
    { word: "דוד בן גוריון", en: "David Ben Gurion", category: "head_of_state" },
    { word: "גולדה מאיר", en: "Golda Meir", category: "head_of_state" },
    { word: "מנחם בגין", en: "Menachem Begin", category: "head_of_state" },
    { word: "שמעון פרס", en: "Shimon Peres", category: "head_of_state" },
    { word: "ברק אובמה", en: "Barack Obama", category: "head_of_state" },
    { word: "דונלד טראמפ", en: "Donald Trump", category: "head_of_state" },
    { word: "ג'ו ביידן", en: "Joe Biden", category: "head_of_state" },
    { word: "ולדימיר פוטין", en: "Vladimir Putin", category: "head_of_state" },
    { word: "עמנואל מקרון", en: "Emmanuel Macron", category: "head_of_state" },
    { word: "בוריס ג'ונסון", en: "Boris Johnson", category: "head_of_state" },
    { word: "אנגלה מרקל", en: "Angela Merkel", category: "head_of_state" },
    { word: "ווינסטון צ'רצ'יל", en: "Winston Churchill", category: "head_of_state" },
    { word: "אברהם לינקולן", en: "Abraham Lincoln", category: "head_of_state" },
    { word: "נלסון מנדלה", en: "Nelson Mandela", category: "head_of_state" },
    { word: "יאיר לפיד", en: "Yair Lapid", category: "politician" },
    { word: "בני גנץ", en: "Benny Gantz", category: "politician" },
    { word: "אביגדור ליברמן", en: "Avigdor Lieberman", category: "politician" },
    { word: "אריה דרעי", en: "Aryeh Deri", category: "politician" },
    { word: "איתמר בן גביר", en: "Itamar Ben Gvir", category: "politician" },
    { word: "בצלאל סמוטריץ'", en: "Bezalel Smotrich", category: "politician" },
    { word: "מרב מיכאלי", en: "Merav Michaeli", category: "politician" },
  
    // --- 5. הוגים, עסקים ודמויות תרבות ---
    { word: "אלברט איינשטיין", en: "Albert Einstein", category: "thinker" },
    { word: "סטיב ג'ובס", en: "Steve Jobs", category: "entrepreneur" },
    { word: "אילון מאסק", en: "Elon Musk", category: "entrepreneur" },
    { word: "ביל גייטס", en: "Bill Gates", category: "entrepreneur" },
    { word: "מארק צוקרברג", en: "Mark Zuckerberg", category: "entrepreneur" },
    { word: "ג'ף בזוס", en: "Jeff Bezos", category: "entrepreneur" },
    { word: "וולט דיסני", en: "Walt Disney", category: "entrepreneur" },
    { word: "סטיבן ספילברג", en: "Steven Spielberg", category: "director" },
    { word: "וולטר ווייט", en: "Walter White", category: "tv_character" },
    { word: "הומר סימפסון", en: "Homer Simpson", category: "cartoon_character" },
    { word: "באטמן", en: "Batman", category: "superhero" },
    { word: "ספיידרמן", en: "Spider-Man", category: "superhero" },
    { word: "נובאק ג'וקוביץ'", en: "Novak Djokovic", category: "tennis_player" },
    { word: "רפאל נדאל", en: "Rafael Nadal", category: "tennis_player" },
    { word: "סטפן קרי", en: "Stephen Curry", category: "basketballer" },
    { word: "קובי בראיינט", en: "Kobe Bryant", category: "basketballer" },
    { word: "שאקיל אוניל", en: "Shaquille O'Neal", category: "basketballer" },
    { word: "עומרי כספי", en: "Omri Casspi", category: "basketballer" },
    { word: "מיקי ברקוביץ'", en: "Miki Berkovich", category: "basketballer" },
    { word: "דורון ג'מצ'י", en: "Doron Jamchi", category: "basketballer" },
    { word: "טל ברודי", en: "Tal Brody", category: "basketballer" },
    { word: "ים מדר", en: "Yam Madar", category: "basketballer" },
    { word: "טייגר וודס", en: "Tiger Woods", category: "olympic_athlete" },
    { word: "סימון ביילס", en: "Simone Biles", category: "olympic_athlete" },
    { word: "ארטיום דולגופיאט", en: "Artem Dolgopyat", category: "olympic_athlete" },
    { word: "אריק זאבי", en: "Ariel Zeevi", category: "olympic_athlete" },
    { word: "יעל ארד", en: "Yael Arad", category: "olympic_athlete" },
    { word: "אורי ששון", en: "Ori Sasson", category: "olympic_athlete" },
    { word: "שגיא מוקי", en: "Sagi Muki", category: "olympic_athlete" },
    { word: "וורן באפט", en: "Warren Buffett", category: "entrepreneur" },
    { word: "ריצ'רד ברנסון", en: "Richard Branson", category: "entrepreneur" },
    { word: "סטף ורטהיימר", en: "Stef Wertheimer", category: "entrepreneur" },
    { word: "שרי אריסון", en: "Shari Arison", category: "entrepreneur" },
    { word: "יצחק תשובה", en: "Yitzhak Tshuva", category: "entrepreneur" },
    { word: "עידן עופר", en: "Idan Ofer", category: "entrepreneur" },
    { word: "רמי לוי", en: "Rami Levy", category: "entrepreneur" },
    { word: "מרקו פולו", en: "Marco Polo", category: "historical_figure" },
    { word: "כריסטופר קולומבוס", en: "Christopher Columbus", category: "historical_figure" },
    { word: "ניל ארמסטרונג", en: "Neil Armstrong", category: "historical_figure" },
    { word: "מרי קירי", en: "Marie Curie", category: "thinker" },
    { word: "צ'ארלס דרווין", en: "Charles Darwin", category: "thinker" },
    { word: "גלילאו גליליי", en: "Galileo Galilei", category: "thinker" },
    { word: "סוקרטס", en: "Socrates", category: "thinker" },
    { word: "אריסטו", en: "Aristotle", category: "thinker" },
    { word: "אפלטון", en: "Plato", category: "thinker" },
    { word: "מהטמה גנדי", en: "Mahatma Gandhi", category: "historical_figure" },
    { word: "מרטין לותר", en: "Martin Luther", category: "historical_figure" },
    { word: "ארז טל", en: "Erez Tal", category: "journalist" },
    { word: "אברי גלעד", en: "Avri Gilad", category: "journalist" },
    { word: "צביקה הדר", en: "Zvika Hadar", category: "actor" },
    { word: "מירי מסיקה", en: "Miri Mesika", category: "singer" },
    { word: "קרן פלס", en: "Keren Peles", category: "singer" },
    { word: "אבי קושניר", en: "Avi Kushnir", category: "actor" },
    { word: "מוני מושונוב", en: "Moni Moshonov", category: "actor" },
    { word: "שלמה בראבא", en: "Shlomo Baraba", category: "actor" },
    { word: "דב נבון", en: "Dov Navon", category: "actor" },
    { word: "קרן מור", en: "Keren Mor", category: "actor" },
    { word: "אילנה דיין", en: "Ilana Dayan", category: "journalist" },
    { word: "רפי רשף", en: "Rafi Reshef", category: "journalist" },
    { word: "עודד בן עמי", en: "Oded Ben-Ami", category: "journalist" },
    { word: "אמנון לוי", en: "Amnon Levi", category: "journalist" },
    { word: "חיים אתגר", en: "Haim Etgar", category: "journalist" },
    { word: "ניב רסקין", en: "Niv Raskin", category: "journalist" },
    { word: "אדיר מילר", en: "Adir Miller", category: "actor" },
    { word: "ליטל שוורץ", en: "Lital Schwartz", category: "actor" },
    { word: "ישראל קטורזה", en: "Israel Katorza", category: "actor" },
    { word: "אלי פיניש", en: "Eli Finish", category: "actor" },
    { word: "מריאנו אידלמן", en: "Mariano Idelman", category: "actor" },
    { word: "עלמה זק", en: "Alma Zack", category: "actor" },
    { word: "שני כהן", en: "Shani Cohen", category: "actor" },
    { word: "ליאת הר לב", en: "Liat Har Lev", category: "actor" },
    { word: "יניב ביטון", en: "Yaniv Biton", category: "actor" },
    { word: "ערן זרחוביץ'", en: "Eran Zarahovitsh", category: "actor" },
    { word: "מאור כהן", en: "Maor Cohen", category: "actor" },
    { word: "טל פרידמן", en: "Tal Friedman", category: "actor" },
    { word: "איל קיציס", en: "Eyal Kitzis", category: "actor" },
    { word: "יובל סמו", en: "Yuval Semo", category: "actor" },
    { word: "רועי בר נתן", en: "Roey Bar-Natan", category: "actor" },
    { word: "אילן פלד", en: "Ilan Peled", category: "actor" },
    { word: "יעקב כהן", en: "Yaakov Cohen", category: "actor" },
    { word: "צחי נוי", en: "Zachi Noy", category: "actor" },
    { word: "יהודה בארקן", en: "Yehuda Barkan", category: "actor" },
    { word: "זאב רווח", en: "Zeev Revach", category: "actor" },
    { word: "טוביה צפיר", en: "Tuvia Tzafir", category: "actor" },
    { word: "ספי ריבלין", en: "Sefi Rivlin", category: "actor" },
    { word: "דודו טופז", en: "Dudu Topaz", category: "actor" },
    { word: "דנזל וושינגטון", en: "Denzel Washington", category: "actor" },
    { word: "ניקול קידמן", en: "Nicole Kidman", category: "actor" },
    { word: "קייט וינסלט", en: "Kate Winslet", category: "actor" },
    { word: "סנדרה בולוק", en: "Sandra Bullock", category: "actor" },
    { word: "הריסון פורד", en: "Harrison Ford", category: "actor" },
    { word: "סילבסטר סטאלון", en: "Sylvester Stallone", category: "actor" },
    { word: "ארנולד שוורצנגר", en: "Arnold Schwarzenegger", category: "actor" },
    { word: "ג'ק ניקולסון", en: "Jack Nicholson", category: "actor" },
    { word: "אנתוני הופקינס", en: "Anthony Hopkins", category: "actor" },
    { word: "קיאנו ריבס", en: "Keanu Reeves", category: "actor" },
    { word: "יו גרנט", en: "Hugh Grant", category: "actor" },
    { word: "ג'ורג' קלוני", en: "George Clooney", category: "actor" },
    { word: "בן אפלק", en: "Ben Affleck", category: "actor" },
    { word: "מאט דיימון", en: "Matt Damon", category: "actor" },
    { word: "ג'ייסון סטיית'ם", en: "Jason Statham", category: "actor" },
    { word: "וין דיזל", en: "Vin Diesel", category: "actor" },
    { word: "מארק וולברג", en: "Mark Wahlberg", category: "actor" },
    { word: "ריאן ריינולדס", en: "Ryan Reynolds", category: "actor" },
    { word: "כריס המסוורת'", en: "Chris Hemsworth", category: "actor" },
    { word: "טום הרדי", en: "Tom Hardy", category: "actor" },
    { word: "מרטין לותר קינג", en: "Martin Luther King Jr.", category: "historical_figure" },
    { word: "ג'ון פ. קנדי", en: "John F. Kennedy", category: "head_of_state" },
    { word: "מרגרט תאצ'ר", en: "Margaret Thatcher", category: "head_of_state" },
    { word: "אינדירה גנדי", en: "Indira Gandhi", category: "head_of_state" },
    { word: "פידל קסטרו", en: "Fidel Castro", category: "head_of_state" },
    { word: "צ'ה גווארה", en: "Che Guevara", category: "historical_figure" },
    { word: "יצחק שמיר", en: "Yitzhak Shamir", category: "head_of_state" },
    { word: "עזר ויצמן", en: "Ezer Weizman", category: "head_of_state" },
    { word: "חיים ויצמן", en: "Chaim Weizmann", category: "head_of_state" },
    { word: "תיאודור הרצל", en: "Theodor Herzl", category: "historical_figure" },
    { word: "זאב ז'בוטינסקי", en: "Ze'ev Jabotinsky", category: "historical_figure" },
    { word: "קפטן אמריקה", en: "Captain America", category: "superhero" },
    { word: "הענק הירוק", en: "Hulk", category: "superhero" },
    { word: "תור (מארוול)", en: "Thor", category: "superhero" },
    { word: "בובספוג", en: "SpongeBob SquarePants", category: "cartoon_character" },
    { word: "פטריק (בובספוג)", en: "Patrick Star", category: "cartoon_character" },
    { word: "דונלד דאק", en: "Donald Duck", category: "cartoon_character" },
    { word: "באגס באני", en: "Bugs Bunny", category: "cartoon_character" },
    { word: "פו הדב", en: "Winnie the Pooh", category: "cartoon_character" },
    { word: "אלזה (לשבור את הקרח)", en: "Elsa", category: "cartoon_character" },
    { word: "סימבה (מלך האריות)", en: "Simba", category: "cartoon_character" },
    { word: "ג'יימס בונד", en: "James Bond", category: "movie_character" },
    { word: "שרלוק הולמס", en: "Sherlock Holmes", category: "movie_character" },
    { word: "אלבוס דמבלדור", en: "Albus Dumbledore", category: "movie_character" },
    { word: "וולדמורט", en: "Voldemort", category: "movie_character" },
    { word: "קאטניס אוורדין", en: "Katniss Everdeen", category: "movie_character" },
    { word: "פורסט גאמפ", en: "Forrest Gump", category: "movie_character" },
    { word: "רוקי בלבואה", en: "Rocky Balboa", category: "movie_character" },
    { word: "שרה קונור", en: "Sarah Connor", category: "movie_character" },
    { word: "מר וולף (ספרות זולה)", en: "The Wolf", category: "movie_character" },
    { word: "טיילר דרדן (מועדון קרב)", en: "Tyler Durden", category: "movie_character" },
    { word: "קארים עבדול-ג'באר", en: "Kareem Abdul-Jabbar", category: "basketballer" },
    { word: "מג'יק ג'ונסון", en: "Magic Johnson", category: "basketballer" },
    { word: "לארי בירד", en: "Larry Bird", category: "basketballer" },
    { word: "דיאגו סימאונה", en: "Diego Simeone", category: "footballer" },
    { word: "פפ גווארדיולה", en: "Pep Guardiola", category: "footballer" },
    { word: "יורגן קלופ", en: "Jurgen Klopp", category: "footballer" },
    { word: "אלכס פרגוסון", en: "Alex Ferguson", category: "footballer" },
    { word: "מיכאל שומאכר", en: "Michael Schumacher", category: "racing_driver" },
    { word: "לואיס המילטון", en: "Lewis Hamilton", category: "racing_driver" },
    { word: "איירטון סנה", en: "Ayrton Senna", category: "racing_driver" },
    { word: "לוי אשכול", en: "Levi Eshkol", category: "head_of_state" },
    { word: "משה שרת", en: "Moshe Sharett", category: "head_of_state" },
    { word: "פנחס ספיר", en: "Pinhas Sapir", category: "politician" },
    { word: "גאולה כהן", en: "Geula Cohen", category: "politician" },
    { word: "שולמית אלוני", en: "Shulamit Aloni", category: "politician" },
    { word: "יוסי שריד", en: "Yossi Sarid", category: "politician" },
    { word: "רפאל איתן (רפול)", en: "Rafael Eitan", category: "historical_figure" },
    { word: "חיים בר-לב", en: "Haim Bar-Lev", category: "historical_figure" },
    { word: "מרדכי גור (מוטה)", en: "Mordechai Gur", category: "historical_figure" },
    { word: "דן חלוץ", en: "Dan Halutz", category: "historical_figure" },
    { word: "גבי אשכנזי", en: "Gabi Ashkenazi", category: "historical_figure" },
    { word: "אביב כוכבי", en: "Aviv Kochavi", category: "historical_figure" },
    { word: "הרצי הלוי", en: "Herzi Halevi", category: "historical_figure" },
    { word: "ניקולה טסלה", en: "Nikola Tesla", category: "thinker" },
    { word: "סטיבן הוקינג", en: "Stephen Hawking", category: "thinker" },
    { word: "פרידריך ניטשה", en: "Friedrich Nietzsche", category: "thinker" },
    { word: "רנה דקארט", en: "Rene Descartes", category: "thinker" },
    { word: "עמנואל קאנט", en: "Immanuel Kant", category: "thinker" },
    { word: "קרל מרקס", en: "Karl Marx", category: "thinker" },
    { word: "ז'אן ז'אק רוסו", en: "Jean-Jacques Rousseau", category: "thinker" },
    { word: "אברהם אבינו", en: "Abraham", category: "biblical" },
    { word: "יצחק אבינו", en: "Isaac", category: "biblical" },
    { word: "יעקב אבינו", en: "Jacob", category: "biblical" },
    { word: "רחל אמנו", en: "Rachel", category: "biblical" },
    { word: "לאה אמנו", en: "Leah", category: "biblical" },
    { word: "יוסף הצדיק", en: "Joseph", category: "biblical" },
    { word: "יהושע בן נון", en: "Joshua", category: "biblical" },
    { word: "שלמה המלך", en: "King Solomon", category: "biblical" },
    { word: "מרדכי היהודי", en: "Mordechai", category: "biblical" },
    { word: "אסתר המלכה", en: "Queen Esther", category: "biblical" },
    { word: "יהודה המכבי", en: "Judah Maccabee", category: "biblical" },
    { word: "בר כוכבא", en: "Bar Kokhba", category: "historical_figure" },
    { word: "רש\"י", en: "Rashi", category: "thinker" },
    { word: "הרמב\"ם", en: "Maimonides", category: "thinker" },
    { word: "שירה האס", en: "Shira Haas", category: "actor" },
    { word: "עמוס תמם", en: "Amos Tamam", category: "actor" },
    { word: "יעל אבקסיס", en: "Yael Abecassis", category: "actor" },
    { word: "רונית אלקבץ", en: "Ronit Elkabetz", category: "actor" },
    { word: "חנה לסלאו", en: "Hanna Laslo", category: "actor" },
    { word: "ציפי שביט", en: "Tzipi Shavit", category: "actor" },
    { word: "יוסי פולק", en: "Yossi Pollak", category: "actor" },
    { word: "ששון גבאי", en: "Sasson Gabai", category: "actor" },
    { word: "מנשה נוי", en: "Menashe Noy", category: "actor" },
    { word: "רמי הויברגר", en: "Rami Heuberger", category: "actor" },
    { word: "הית' לדג'ר", en: "Heath Ledger", category: "actor" },
    { word: "חואקין פיניקס", en: "Joaquin Phoenix", category: "actor" },
    { word: "כריסטיאן בייל", en: "Christian Bale", category: "actor" },
    { word: "בנדיקט קמברבאץ'", en: "Benedict Cumberbatch", category: "actor" },
    { word: "רוברט דאוני ג'וניור", en: "Robert Downey Jr.", category: "actor" },
    { word: "סמואל ל. ג'קסון", en: "Samuel L. Jackson", category: "actor" },
    { word: "ליאם ניסן", en: "Liam Neeson", category: "actor" },
    { word: "דניאל קרייג", en: "Daniel Craig", category: "actor" },
    { word: "פירס ברוסנן", en: "Pierce Brosnan", category: "actor" },
    { word: "שון קונרי", en: "Sean Connery", category: "actor" },
    { word: "רוג'ר מור", en: "Roger Moore", category: "actor" },
    { word: "ג'ים קארי", en: "Jim Carrey", category: "actor" },
    { word: "אדם סנדלר", en: "Adam Sandler", category: "actor" },
    { word: "בן סטילר", en: "Ben Stiller", category: "actor" },
    { word: "אדי מרפי", en: "Eddie Murphy", category: "actor" },
    { word: "סאשה ברון כהן", en: "Sacha Baron Cohen", category: "actor" },
    { word: "ג'ק בלאק", en: "Jack Black", category: "actor" },
    { word: "סת' רוגן", en: "Seth Rogen", category: "actor" },
    { word: "ג'ונה היל", en: "Jonah Hill", category: "actor" },
    { word: "ויל פרל", en: "Will Ferrell", category: "actor" },
    { word: "סטיב קארל", en: "Steve Carell", category: "actor" },
    { word: "קווין הארט", en: "Kevin Hart", category: "actor" },
    { word: "מליסה מקארתי", en: "Melissa McCarthy", category: "actor" },
    { word: "איימי שומר", en: "Amy Schumer", category: "actor" },
    { word: "טינה פיי", en: "Tina Fey", category: "actor" },
    { word: "אמילי בלאנט", en: "Emily Blunt", category: "actor" },
    { word: "אן האת'וויי", en: "Anne Hathaway", category: "actor" },
    { word: "ג'ינה רודריגז", en: "Gina Rodriguez", category: "actor" },
    { word: "סופיה ורגרה", en: "Sofia Vergara", category: "actor" },
    { word: "פנלופה קרוז", en: "Penelope Cruz", category: "actor" },
    { word: "סלמה הייק", en: "Salma Hayek", category: "actor" },
    { word: "חאווייר ברדם", en: "Javier Bardem", category: "actor" },
    { word: "אנטוניו בנדרס", en: "Antonio Banderas", category: "actor" },
    { word: "ריצ'רד גיר", en: "Richard Gere", category: "actor" },
    { word: "ריס וית'רספון", en: "Reese Witherspoon", category: "actor" },
    { word: "דרו ברימור", en: "Drew Barrymore", category: "actor" },
    { word: "קמרון דיאז", en: "Cameron Diaz", category: "actor" },
    { word: "לוסי לו", en: "Lucy Liu", category: "actor" },
    { word: "ג'קי צ'אן", en: "Jackie Chan", category: "actor" },
    { word: "ברוס לי", en: "Bruce Lee", category: "actor" },
    { word: "ג'ט לי", en: "Jet Li", category: "actor" },
    { word: "צ'אק נוריס", en: "Chuck Norris", category: "actor" },
    { word: "ז'אן קלוד ואן דאם", en: "Jean-Claude Van Damme", category: "actor" },
    { word: "סטיבן סיגל", en: "Steven Seagal", category: "actor" },
    { word: "דולף לונדגרן", en: "Dolph Lundgren", category: "actor" },
    { word: "קלינט איסטווד", en: "Clint Eastwood", category: "actor" },
    { word: "ג'ון וויין", en: "John Wayne", category: "actor" },
    { word: "מרלון ברנדו", en: "Marlon Brando", category: "actor" },
    { word: "ג'יימס דין", en: "James Dean", category: "actor" },
    { word: "המפרי בוגרט", en: "Humphrey Bogart", category: "actor" },
    { word: "אודרי הפבורן", en: "Audrey Hepburn", category: "actor" },
    { word: "מרילין מונרו", en: "Marilyn Monroe", category: "actor" },
    { word: "אליזבת טיילור", en: "Elizabeth Taylor", category: "actor" },
    { word: "גרייס קלי", en: "Grace Kelly", category: "actor" },
    { word: "קתרין הפבורן", en: "Katharine Hepburn", category: "actor" },
    { word: "בטי דייוויס", en: "Bette Davis", category: "actor" },
    { word: "שירלי טמפל", en: "Shirley Temple", category: "actor" },
    { word: "תמר איש שלום", en: "Tamar Ish Shalom", category: "journalist" },
    { word: "הילה קורח", en: "Hila Korach", category: "journalist" },
    { word: "אודי סגל", en: "Udi Segal", category: "journalist" },
    { word: "קרן מרציאנו", en: "Keren Marciano", category: "journalist" },
    { word: "עמית סגל", en: "Amit Segal", category: "journalist" },
    { word: "רביב דרוקר", en: "Raviv Drucker", category: "journalist" },
    { word: "אילה חסון", en: "Ayala Hasson", category: "journalist" },
    { word: "גיא פלג", en: "Guy Peleg", category: "journalist" },
    { word: "משה נוסבאום", en: "Moshe Nussbaum", category: "journalist" },
    { word: "רוני דניאל", en: "Roni Daniel", category: "journalist" },
    { word: "ניר דבורי", en: "Nir Dvori", category: "journalist" },
    { word: "אוהד חמו", en: "Ohad Hemo", category: "journalist" },
    { word: "אלון בן דוד", en: "Alon Ben-David", category: "journalist" },
    { word: "יואב לימור", en: "Yoav Limor", category: "journalist" },
    { word: "צופית גרנט", en: "Tzufit Grant", category: "journalist" },
    { word: "אורלי וילנאי", en: "Orly Vilnai", category: "journalist" },
    { word: "גיא מרוז", en: "Guy Meroz", category: "journalist" },
    { word: "גלית גוטמן", en: "Galit Gutman", category: "journalist" },
    { word: "אילנית לוי", en: "Ilanit Levi", category: "actor" },
    { word: "ג'ובאני רוסו", en: "Giovanni Rosso", category: "actor" },
    { word: "מאיה בצלאל", en: "Maya Bezalel", category: "actor" },
    { word: "קותי סבג", en: "Kuti Sabag", category: "actor" },
    { word: "אלירז שדה", en: "Eliraz Sade", category: "actor" },
    { word: "טהוניה רובל", en: "Tahounia Rubel", category: "actor" },
    { word: "שי מיקה", en: "Shai Mika", category: "actor" },
    { word: "אביבית בר זוהר", en: "Avivit Bar Zohar", category: "actor" },
    { word: "ליהיא גרינר", en: "Lehia Griner", category: "actor" },
    { word: "דנה אינטרנשיונל", en: "Dana International", category: "singer" },
    { word: "עדי הימלבלוי", en: "Adi Himelbloy", category: "actor" },
    { word: "דון לני גבאי", en: "Dawn Lanny-Gabay", category: "actor" },
    { word: "שירה נאור", en: "Shira Naor", category: "actor" },
    { word: "גאיה שליטא כץ", en: "Gaya Shalita Katz", category: "actor" },
    { word: "לי בירן", en: "Lee Biran", category: "singer" },
    { word: "אליאנה תדהר", en: "Eliana Tidhar", category: "actor" },
    { word: "תובל שפיר", en: "Tuval Shafir", category: "actor" },
    { word: "דניאל מורשת", en: "Daniel Moreshet", category: "actor" },
    { word: "שירן סנדל", en: "Shiran Sendel", category: "actor" },
    { word: "עומר דרור", en: "Omer Dror", category: "actor" },
    { word: "דר זוזובסקי", en: "Dar Zuzovsky", category: "actor" },
    { word: "ניב סולטן", en: "Niv Sultan", category: "actor" },
    { word: "מאור שוויצר", en: "Maor Schweizer", category: "actor" },
    { word: "דניאל גד", en: "Daniel Gad", category: "actor" },
    { word: "ישראל אטיאס", en: "Israel Atias", category: "actor" },
    { word: "עופר חיון", en: "Ofer Hayoun", category: "actor" },
    { word: "מורן אטיאס", en: "Moran Atias", category: "actor" },
    { word: "חן אמסלם", en: "Chen Amsalem", category: "actor" },
    { word: "מגי אזרזר", en: "Maggie Azarzar", category: "actor" },
    { word: "אניה בוקשטיין", en: "Ania Bukstein", category: "actor" },
    { word: "שני קליין", en: "Shani Klein", category: "actor" },
    { word: "נלי תגר", en: "Nelly Tagar", category: "actor" },
    { word: "יבגניה דודינה", en: "Evgenia Dodina", category: "actor" },
    { word: "לאורה ריבלין", en: "Laura Rivlin", category: "actor" },
    { word: "סנדרה שדה", en: "Sandra Sade", category: "actor" },
    { word: "דבורה קידר", en: "Dvora Kedar", category: "actor" },
    { word: "ליא קניג", en: "Lea Koenig", category: "actor" },
    { word: "גילה אלמגור", en: "Gila Almagor", category: "actor" },
    { word: "מרים זוהר", en: "Miriam Zohar", category: "actor" },
    { word: "רבקה מיכאלי", en: "Rivka Michaeli", category: "actor" },
    { word: "חנה מרון", en: "Hanna Maron", category: "actor" },
    { word: "תיקי דיין", en: "Tiki Dayan", category: "actor" },
    { word: "אלי יצפאן", en: "Eli Yatzpan", category: "actor" },
    { word: "גדי יגיל", en: "Gadi Yagil", category: "actor" },
    { word: "שלישיית הגשש החיוור", en: "HaGashash HaHiver", category: "actor" },
    { word: "שייקה לוי", en: "Shaike Levi", category: "actor" },
    { word: "גברי בנאי", en: "Gavri Banai", category: "actor" },
    { word: "ישראל פוליאקוב (פולי)", en: "Yisrael Poliakov", category: "actor" },
    { word: "גיה באר גורביץ'", en: "Gia Beer Gurevich", category: "actor" },
    { word: "תום אהרון", en: "Tom Aharon", category: "actor" },
    { word: "גורי אלפי", en: "Guri Alfi", category: "actor" },
    { word: "ליאור שליין", en: "Lior Schleien", category: "actor" },
    { word: "מרב פלדמן", en: "Merav Feldman", category: "actor" },
    { word: "עידו רוזנבלום", en: "Ido Rosenblum", category: "actor" },
    { word: "דידי הררי", en: "Didi Harari", category: "journalist" },
    { word: "נתן זהבי", en: "Natan Zahavi", category: "journalist" },
    { word: "ליאור דיין", en: "Lior Dayan", category: "journalist" },
    { word: "חנוך דאום", en: "Hanoch Daum", category: "journalist" },
    { word: "קווין דה בריינה", en: "Kevin De Bruyne", category: "footballer" },
    { word: "ויניסיוס ג'וניור", en: "Vinicius Jr.", category: "footballer" },
    { word: "ג'וד בלינגהאם", en: "Jude Bellingham", category: "footballer" },
    { word: "יוהאן קרויף", en: "Johan Cruyff", category: "footballer" },
    { word: "פרנץ בקנבאואר", en: "Franz Beckenbauer", category: "footballer" },
    { word: "רונאלדו (הברזילאי)", en: "Ronaldo Nazario", category: "footballer" },
    { word: "מישל פלאטיני", en: "Michel Platini", category: "footballer" },
    { word: "מרקו ואן באסטן", en: "Marco van Basten", category: "footballer" },
    { word: "אאוזביו", en: "Eusebio", category: "footballer" },
    { word: "ג'ורג' בסט", en: "George Best", category: "footballer" },
    { word: "בובי צ'רלטון", en: "Bobby Charlton", category: "footballer" },
    { word: "תיירי הנרי", en: "Thierry Henry", category: "footballer" },
    { word: "סטיבן ג'רארד", en: "Steven Gerrard", category: "footballer" },
    { word: "פרנק למפארד", en: "Frank Lampard", category: "footballer" },
    { word: "וויין רוני", en: "Wayne Rooney", category: "footballer" },
    { word: "ראול", en: "Raul", category: "footballer" },
    { word: "קרלס פויול", en: "Carles Puyol", category: "footballer" },
    { word: "ג'אנלואיג'י בופון", en: "Gianluigi Buffon", category: "footballer" },
    { word: "פאולו מלדיני", en: "Paolo Maldini", category: "footballer" },
    { word: "פרנצ'סקו טוטי", en: "Francesco Totti", category: "footballer" },
    { word: "אלסנדרו דל פיירו", en: "Alessandro Del Piero", category: "footballer" },
    { word: "אנדראה פירלו", en: "Andrea Pirlo", category: "footballer" },
    { word: "פיליפ לאם", en: "Philipp Lahm", category: "footballer" },
    { word: "תומאס מילר", en: "Thomas Muller", category: "footballer" },
    { word: "מנואל נוייר", en: "Manuel Neuer", category: "footballer" },
    { word: "אבי נמני", en: "Avi Nimni", category: "footballer" },
    { word: "אייל ברקוביץ'", en: "Eyal Berkovic", category: "footballer" },
    { word: "חיים רביבו", en: "Haim Revivo", category: "footballer" },
    { word: "ראובן עטר", en: "Reuven Atar", category: "footballer" },
    { word: "מוטל'ה שפיגלר", en: "Mordechai Spiegler", category: "footballer" },
    { word: "משה דיין", en: "Moshe Dayan", category: "historical_figure" },
    { word: "אריאל שרון", en: "Ariel Sharon", category: "head_of_state" },
    { word: "יצחק נבון", en: "Yitzhak Navon", category: "head_of_state" },
    { word: "זלמן שזר", en: "Zalman Shazar", category: "head_of_state" },
    { word: "אפרים קציר", en: "Ephraim Katzir", category: "head_of_state" },
    { word: "ראובן ריבלין", en: "Reuven Rivlin", category: "head_of_state" },
    { word: "בוז'י הרצוג", en: "Isaac Herzog", category: "head_of_state" },
    { word: "נפתלי בנט", en: "Naftali Bennett", category: "politician" },
    { word: "אהוד ברק", en: "Ehud Barak", category: "head_of_state" },
    { word: "אהוד אולמרט", en: "Ehud Olmert", category: "head_of_state" },
    { word: "גדעון סער", en: "Gideon Sa'ar", category: "politician" },
    { word: "זהבה גלאון", en: "Zehava Galon", category: "politician" },
    { word: "איילת שקד", en: "Ayelet Shaked", category: "politician" },
    { word: "ציפי לבני", en: "Tzipi Livni", category: "politician" },
    { word: "שלי יחימוביץ'", en: "Shelly Yachimovich", category: "politician" },
    { word: "עמיר פרץ", en: "Amir Peretz", category: "politician" },
    { word: "ביל קלינטון", en: "Bill Clinton", category: "head_of_state" },
    { word: "ג'ורג' וו. בוש", en: "George W. Bush", category: "head_of_state" },
    { word: "רונלד רייגן", en: "Ronald Reagan", category: "head_of_state" },
    { word: "פרנקלין ד. רוזוולט", en: "Franklin D. Roosevelt", category: "head_of_state" },
    { word: "ג'ורג' וושינגטון", en: "George Washington", category: "head_of_state" },
    { word: "בוריס ילצין", en: "Boris Yeltsin", category: "head_of_state" },
    { word: "מיכאיל גורבצ'וב", en: "Mikhail Gorbachev", category: "head_of_state" },
    { word: "יוסיף סטלין", en: "Joseph Stalin", category: "head_of_state" },
    { word: "לנין", en: "Lenin", category: "historical_figure" },
    { word: "ניקיטה חרושצ'וב", en: "Nikita Khrushchev", category: "head_of_state" },
    { word: "טוני בלייר", en: "Tony Blair", category: "head_of_state" },
    { word: "רישי סונאק", en: "Rishi Sunak", category: "head_of_state" },
    { word: "המלכה אליזבת השנייה", en: "Queen Elizabeth II", category: "head_of_state" },
    { word: "המלך צ'ארלס השלישי", en: "King Charles III", category: "head_of_state" },
    { word: "הנסיכה דיאנה", en: "Princess Diana", category: "historical_figure" },
    { word: "פרנסואה הולנד", en: "Francois Hollande", category: "head_of_state" },
    { word: "ניקולא סרקוזי", en: "Nicolas Sarkozy", category: "head_of_state" },
    { word: "ז'אק שיראק", en: "Jacques Chirac", category: "head_of_state" },
    { word: "שארל דה גול", en: "Charles de Gaulle", category: "head_of_state" },
    { word: "אולף שולץ", en: "Olaf Scholz", category: "head_of_state" },
    { word: "הלמוט קוהל", en: "Helmut Kohl", category: "head_of_state" },
    { word: "קונראד אדנאואר", en: "Konrad Adenauer", category: "head_of_state" },
    { word: "נפולאון בונפרטה", en: "Napoleon Bonaparte", category: "historical_figure" },
    { word: "יוליוס קיסר", en: "Julius Caesar", category: "historical_figure" },
    { word: "אלכסנדר הגדול", en: "Alexander the Great", category: "historical_figure" },
    { word: "ג'ינגיס חאן", en: "Genghis Khan", category: "historical_figure" },
    { word: "קלאופטרה", en: "Cleopatra", category: "historical_figure" },
    { word: "מארי אנטואנט", en: "Marie Antoinette", category: "historical_figure" },
    { word: "ז'אן ד'ארק", en: "Joan of Arc", category: "historical_figure" },
    { word: "מלקולם אקס", en: "Malcolm X", category: "historical_figure" },
    { word: "חו מנהיג (הו צ'י מין)", en: "Ho Chi Minh", category: "head_of_state" },
    { word: "מאו דזה-דונג", en: "Mao Zedong", category: "head_of_state" },
    { word: "שי ג'ינפינג", en: "Xi Jinping", category: "head_of_state" },
    { word: "הירוהיטו", en: "Hirohito", category: "head_of_state" },
    { word: "קים ג'ונג-און", en: "Kim Jong-un", category: "head_of_state" },
    { word: "קים ג'ונג-איל", en: "Kim Jong-il", category: "head_of_state" },
    { word: "קים איל-סונג", en: "Kim Il-sung", category: "head_of_state" },
    { word: "אנואר סאדאת", en: "Anwar Sadat", category: "head_of_state" },
    { word: "חוסני מובארק", en: "Hosni Mubarak", category: "head_of_state" },
    { word: "גמאל עבד אל נאצר", en: "Gamal Abdel Nasser", category: "head_of_state" },
    { word: "המלך חוסיין", en: "King Hussein", category: "head_of_state" },
    { word: "המלך עבדאללה", en: "King Abdullah", category: "head_of_state" },
    { word: "יאסר ערפאת", en: "Yasser Arafat", category: "head_of_state" },
    { word: "סדאם חוסיין", en: "Saddam Hussein", category: "head_of_state" },
    { word: "מועמר קדאפי", en: "Muammar Gaddafi", category: "head_of_state" },
    { word: "באשר אל-אסד", en: "Bashar al-Assad", category: "head_of_state" },
    { word: "חאפז אל-אסד", en: "Hafez al-Assad", category: "head_of_state" },
    { word: "אייתוללה חומייני", en: "Ayatollah Khomeini", category: "head_of_state" },
    { word: "עלי ח'אמנאי", en: "Ali Khamenei", category: "head_of_state" },
    { word: "צלאח א-דין", en: "Saladin", category: "historical_figure" },
    { word: "סולימאן המפואר", en: "Suleiman the Magnificent", category: "historical_figure" },
    { word: "המלכה ויקטוריה", en: "Queen Victoria", category: "head_of_state" },
    { word: "הנרי השמיני", en: "Henry VIII", category: "head_of_state" },
    { word: "אליזבת הראשונה", en: "Elizabeth I", category: "head_of_state" },
    { word: "לואי ה-14", en: "Louis XIV", category: "head_of_state" },
    { word: "לואי ה-16", en: "Louis XVI", category: "head_of_state" },
    { word: "צאר ניקולאי השני", en: "Tsar Nicholas II", category: "head_of_state" },
    { word: "פיוטר הגדול", en: "Peter the Great", category: "head_of_state" },
    { word: "יקתרינה הגדולה", en: "Catherine the Great", category: "head_of_state" },
    { word: "ביסמרק", en: "Otto von Bismarck", category: "head_of_state" },
    { word: "פרדיננד מגלן", en: "Ferdinand Magellan", category: "historical_figure" },
    { word: "ואסקו דה גאמה", en: "Vasco da Gama", category: "historical_figure" },
    { word: "אמריגו וספוצ'י", en: "Amerigo Vespucci", category: "historical_figure" },
    { word: "קפטן קוק", en: "James Cook", category: "historical_figure" },
    { word: "רואלד אמונדסן", en: "Roald Amundsen", category: "historical_figure" },
    { word: "באז אולדרין", en: "Buzz Aldrin", category: "historical_figure" },
    { word: "יורי גגארין", en: "Yuri Gagarin", category: "historical_figure" },
    { word: "אילן רמון", en: "Ilan Ramon", category: "historical_figure" },
    { word: "לאונרדו דה וינצ'י", en: "Leonardo da Vinci", category: "thinker" },
    { word: "מיכלאנג'לו", en: "Michelangelo", category: "thinker" },
    { word: "רפאל (אמן)", en: "Raphael", category: "thinker" },
    { word: "דונטלו", en: "Donatello", category: "thinker" },
    { word: "וינסנט ואן גוך", en: "Vincent van Gogh", category: "thinker" },
    { word: "פאבלו פיקאסו", en: "Pablo Picasso", category: "thinker" },
    { word: "סלבדור דאלי", en: "Salvador Dali", category: "thinker" },
    { word: "קלוד מונה", en: "Claude Monet", category: "thinker" },
    { word: "רמברנדט", en: "Rembrandt", category: "thinker" },
    { word: "יוהאן סבסטיאן באך", en: "Johann Sebastian Bach", category: "thinker" },
    { word: "וולפגנג אמדאוס מוצרט", en: "Wolfgang Amadeus Mozart", category: "thinker" },
    { word: "לודוויג ואן בטהובן", en: "Ludwig van Beethoven", category: "thinker" },
    { word: "פרדריק שופן", en: "Frederic Chopin", category: "thinker" },
    { word: "פיוטר איליץ' צ'ייקובסקי", en: "Pyotr Ilyich Tchaikovsky", category: "thinker" },
    { word: "ג'וזפה ורדי", en: "Giuseppe Verdi", category: "thinker" },
    { word: "ריכרד וגנר", en: "Richard Wagner", category: "thinker" },
    { word: "איגור סטרווינסקי", en: "Igor Stravinsky", category: "thinker" },
    { word: "וויליאם שייקספיר", en: "William Shakespeare", category: "thinker" },
    { word: "מיגל דה סרוואנטס", en: "Miguel de Cervantes", category: "thinker" },
    { word: "דנטה אליגיירי", en: "Dante Alighieri", category: "thinker" },
    { word: "יוהאן וולפגנג פון גתה", en: "Johann Wolfgang von Goethe", category: "thinker" },
    { word: "ויקטור הוגו", en: "Victor Hugo", category: "thinker" },
    { word: "צ'ארלס דיקנס", en: "Charles Dickens", category: "thinker" },
    { word: "לב טולסטוי", en: "Leo Tolstoy", category: "thinker" },
    { word: "פיודור דוסטויבסקי", en: "Fyodor Dostoevsky", category: "thinker" },
    { word: "אנטון צ'כוב", en: "Anton Chekhov", category: "thinker" },
    { word: "ארנסט המינגוויי", en: "Ernest Hemingway", category: "thinker" },
    { word: "מארק טוויין", en: "Mark Twain", category: "thinker" },
    { word: "פרנץ קפקא", en: "Franz Kafka", category: "thinker" },
    { word: "ז'אן-פול סארטר", en: "Jean-Paul Sartre", category: "thinker" },
    { word: "אלבר קאמי", en: "Albert Camus", category: "thinker" },
    { word: "סימון דה בובואר", en: "Simone de Beauvoir", category: "thinker" },
    { word: "וירג'יניה וולף", en: "Virginia Woolf", category: "thinker" },
    { word: "אוסקר ויילד", en: "Oscar Wilde", category: "thinker" },
    { word: "ג'ורג' אורוול", en: "George Orwell", category: "thinker" },
    { word: "ג'יי קיי רולינג", en: "J.K. Rowling", category: "thinker" },
    { word: "סטיבן קינג", en: "Stephen King", category: "thinker" },
    { word: "אגאתה כריסטי", en: "Agatha Christie", category: "thinker" },
    { word: "ארתור קונאן דויל", en: "Arthur Conan Doyle", category: "thinker" },
    { word: "הנס כריסטיאן אנדרסן", en: "Hans Christian Andersen", category: "thinker" },
    { word: "האחים גרים", en: "Brothers Grimm", category: "thinker" },
    { word: "ז'ול ורן", en: "Jules Verne", category: "thinker" },
    { word: "אייזק אסימוב", en: "Isaac Asimov", category: "thinker" },
    { word: "ג'. ר. ר. טולקין", en: "J.R.R. Tolkien", category: "thinker" },
    { word: "ש\"י עגנון", en: "S.Y. Agnon", category: "thinker" },
    { word: "חיים נחמן ביאליק", en: "Hayim Nahman Bialik", category: "thinker" },
    { word: "שאול טשרניחובסקי", en: "Saul Tchernichovsky", category: "thinker" },
    { word: "נתן אלתרמן", en: "Natan Alterman", category: "thinker" },
    { word: "אברהם שלונסקי", en: "Avraham Shlonsky", category: "thinker" },
    { word: "לאה גולדברג", en: "Leah Goldberg", category: "thinker" },
    { word: "רחל המשוררת", en: "Rachel Bluwstein", category: "thinker" },
    { word: "עמוס עוז", en: "Amos Oz", category: "thinker" },
    { word: "א.ב. יהושע", en: "A.B. Yehoshua", category: "thinker" },
    { word: "דויד גרוסמן", en: "David Grossman", category: "thinker" },
    { word: "מאיר שלו", en: "Meir Shalev", category: "thinker" },
    { word: "אפרים קישון", en: "Ephraim Kishon", category: "thinker" },
    { word: "חנוך לוין", en: "Hanoch Levin", category: "thinker" },
    { word: "נעמי שמר", en: "Naomi Shemer", category: "thinker" },
    { word: "אהוד מנור", en: "Ehud Manor", category: "thinker" },
    { word: "יוסי גיספן", en: "Yossi Gispan", category: "thinker" },
    { word: "אברהם פריד", en: "Avraham Fried", category: "singer" },
    { word: "מרדכי בן דוד", en: "Mordechai Ben David", category: "singer" },
    { word: "יעקב שוואקי", en: "Yaakov Shwekey", category: "singer" },
    { word: "ישי ריבו", en: "Ishay Ribo", category: "singer" },
    { word: "עמיר בניון", en: "Amir Benayoun", category: "singer" },
    { word: "אביתר בנאי", en: "Eviatar Banai", category: "singer" },
    { word: "שולי רנד", en: "Shuli Rand", category: "singer" },
    { word: "אריק סיני", en: "Arik Sinai", category: "singer" },
    { word: "מירי אלוני", en: "Miri Aloni", category: "singer" },
    { word: "סטיב ווזניאק", en: "Steve Wozniak", category: "entrepreneur" },
    { word: "לארי פייג'", en: "Larry Page", category: "entrepreneur" },
    { word: "סרגיי ברין", en: "Sergey Brin", category: "entrepreneur" },
    { word: "רופרט מרדוק", en: "Rupert Murdoch", category: "entrepreneur" },
    { word: "הנרי פורד", en: "Henry Ford", category: "entrepreneur" },
    { word: "ג'ון ד. רוקפלר", en: "John D. Rockefeller", category: "entrepreneur" },
    { word: "אנדרו קרנגי", en: "Andrew Carnegie", category: "entrepreneur" },
    { word: "קוקו שאנל", en: "Coco Chanel", category: "entrepreneur" },
    { word: "ג'ורג'יו ארמני", en: "Giorgio Armani", category: "entrepreneur" },
    { word: "ראלף לורן", en: "Ralph Lauren", category: "entrepreneur" },
    { word: "ארתור קלארק", en: "Arthur C. Clarke", category: "thinker" },
    { word: "אייזק ניוטון", en: "Isaac Newton", category: "thinker" },
    { word: "תומאס אדיסון", en: "Thomas Edison", category: "thinker" },
    { word: "אלכסנדר גרהם בל", en: "Alexander Graham Bell", category: "thinker" },
    { word: "האחים רייט", en: "Wright Brothers", category: "thinker" },
    { word: "לואי פסטר", en: "Louis Pasteur", category: "thinker" },
    { word: "זיגמונד פרויד", en: "Sigmund Freud", category: "thinker" },
    { word: "קארל יונג", en: "Carl Jung", category: "thinker" },
    { word: "ברוך שפינוזה", en: "Baruch Spinoza", category: "thinker" },
    { word: "וולטר", en: "Voltaire", category: "thinker" },
    { word: "אדם סמית'", en: "Adam Smith", category: "thinker" },
    { word: "תומאס הובס", en: "Thomas Hobbes", category: "thinker" },
    { word: "ג'ון לוק", en: "John Locke", category: "thinker" },
    { word: "פיתגורס", en: "Pythagoras", category: "thinker" },
    { word: "ארכימדס", en: "Archimedes", category: "thinker" },
    { word: "אוקלידס", en: "Euclid", category: "thinker" },
    { word: "קונפוציוס", en: "Confucius", category: "thinker" },
    { word: "לאו דזה", en: "Laozi", category: "thinker" },
    { word: "משה רבנו", en: "Moses", category: "biblical" },
    { word: "דוד המלך", en: "King David", category: "biblical" },
    { word: "יונה הנביא", en: "Jonah", category: "biblical" },
    { word: "אהרן הכהן", en: "Aaron", category: "biblical" },
    { word: "מרים הנביאה", en: "Miriam", category: "biblical" },
    { word: "דבורה הנביאה", en: "Deborah", category: "biblical" },
    { word: "גדעון (שופט)", en: "Gideon", category: "biblical" },
    { word: "דלילה", en: "Delilah", category: "biblical" },
    { word: "רות המואביה", en: "Ruth", category: "biblical" },
    { word: "שמואל הנביא", en: "Samuel", category: "biblical" },
    { word: "שאול המלך", en: "Saul", category: "biblical" },
    { word: "אליהו הנביא", en: "Elijah", category: "biblical" },
    { word: "אלישע הנביא", en: "Elisha", category: "biblical" },
    { word: "ישעיהו הנביא", en: "Isaiah", category: "biblical" },
    { word: "ירמיהו הנביא", en: "Jeremiah", category: "biblical" },
    { word: "יחזקאל הנביא", en: "Ezekiel", category: "biblical" },
    { word: "איוב", en: "Job", category: "biblical" },
    { word: "דניאל (איש חמודות)", en: "Daniel", category: "biblical" },
    { word: "עזרא הסופר", en: "Ezra", category: "biblical" },
    { word: "נחמיה", en: "Nehemiah", category: "biblical" },
    { word: "חנה ושבעת בניה", en: "Hannah and her seven sons", category: "historical_figure" },
    { word: "יוחנן הורקנוס", en: "John Hyrcanus", category: "historical_figure" },
    { word: "אלכסנדר ינאי", en: "Alexander Jannaeus", category: "historical_figure" },
    { word: "שלומציון המלכה", en: "Salome Alexandra", category: "historical_figure" },
    { word: "הורדוס המלך", en: "Herod the Great", category: "historical_figure" },
    { word: "יוסף בן מתתיהו", en: "Josephus", category: "historical_figure" },
    { word: "רבי עקיבא", en: "Rabbi Akiva", category: "historical_figure" },
    { word: "רבי שמעון בר יוחאי", en: "Rabbi Shimon bar Yochai", category: "historical_figure" },
    { word: "רבי יהודה הנשיא", en: "Judah ha-Nasi", category: "historical_figure" },
    { word: "רבי יהודה הלוי", en: "Judah Halevi", category: "thinker" },
    { word: "הבעל שם טוב", en: "Baal Shem Tov", category: "thinker" },
    { word: "הגר\"א (הגאון מוילנה)", en: "Vilna Gaon", category: "thinker" },
    { word: "רבי נחמן מברסלב", en: "Nachman of Breslov", category: "thinker" },
    { word: "הבבא סאלי", en: "Baba Sali", category: "historical_figure" },
    { word: "הרב קוק", en: "Rabbi Kook", category: "thinker" },
    { word: "שרה אהרונסון", en: "Sarah Aaronsohn", category: "historical_figure" },
    { word: "חנה סנש", en: "Hannah Szenes", category: "historical_figure" },
    { word: "אלי כהן (המרגל)", en: "Eli Cohen", category: "historical_figure" },
    { word: "יוני נתניהו", en: "Yonatan Netanyahu", category: "historical_figure" },
    { word: "רונה רמון", en: "Rona Ramon", category: "historical_figure" },
    { word: "רלף קליין", en: "Ralph Klein", category: "basketballer" },
    { word: "יהושע סובול", en: "Yehoshua Sobol", category: "thinker" },
    { word: "נתן זך", en: "Natan Zach", category: "thinker" },
    { word: "דליה רביקוביץ'", en: "Dahlia Ravikovitch", category: "thinker" },
    { word: "יאיר גרבוז", en: "Yair Garbuz", category: "thinker" },
    { word: "מנשה קדישמן", en: "Menashe Kadishman", category: "thinker" },
    { word: "נחום גוטמן", en: "Nahum Gutman", category: "thinker" },
    { word: "ראובן רובין", en: "Reuven Rubin", category: "thinker" },
    { word: "מרסל ינקו", en: "Marcel Janco", category: "thinker" },
    { word: "יעקב אגם", en: "Yaacov Agam", category: "thinker" },
    { word: "עפרה שטראוס", en: "Ofra Strauss", category: "entrepreneur" },
    { word: "גיל שויד", en: "Gil Shwed", category: "entrepreneur" },
    { word: "מריוס נכט", en: "Marius Nacht", category: "entrepreneur" },
    { word: "אמנון שעשוע", en: "Amnon Shashua", category: "entrepreneur" },
    { word: "זיו אבירם", en: "Ziv Aviram", category: "entrepreneur" },
    { word: "דב מורן", en: "Dov Moran", category: "entrepreneur" },
    { word: "איתן ורטהיימר", en: "Eitan Wertheimer", category: "entrepreneur" },
    { word: "דנה וייס", en: "Dana Weiss", category: "journalist" },
    { word: "ברהנו טגניה", en: "Brahanu Tegene", category: "journalist" },
    { word: "סיוון רהב-מאיר", en: "Sivan Rahav-Meir", category: "journalist" },
    { word: "ידידיה מאיר", en: "Yedidya Meir", category: "journalist" },
    { word: "קובי אריאלי", en: "Kobi Arieli", category: "journalist" },
    { word: "ג'קי לוי", en: "Jacky Levy", category: "journalist" },
    { word: "יאיר ניצני", en: "Yair Nitzani", category: "singer" },
    { word: "אלון אולארצ'יק", en: "Alon Oleartchik", category: "singer" },
    { word: "אפרים שמיר", en: "Ephraim Shamir", category: "singer" },
    { word: "יצחק קלפטר", en: "Yitzhak Klepter", category: "singer" },
    { word: "מאיר פניגשטיין", en: "Meir Fenigstein", category: "singer" },
    { word: "רענן שקד", en: "Ra'anan Shaked", category: "journalist" },
    { word: "עדה יונאת", en: "Ada Yonath", category: "thinker" },
    { word: "אהרון צ'חנובר", en: "Aaron Ciechanover", category: "thinker" },
    { word: "אברהם הרשקו", en: "Avram Hershko", category: "thinker" },
    { word: "דן שכטמן", en: "Dan Shechtman", category: "thinker" },
    { word: "רוברט אומן", en: "Robert Aumann", category: "thinker" },
    { word: "אריה ורשל", en: "Arieh Warshel", category: "thinker" },
    { word: "מיכאל לויט", en: "Michael Levitt", category: "thinker" },
    { word: "דניאל כהנמן", en: "Daniel Kahneman", category: "thinker" }
  ];