export const CELEBS_WORDS = [
  // --- 1. זמרים וזמרות (singer) ---
  { word: "שלמה ארצי", en: "Shlomo Artzi", category: "singer" },
  { word: "אייל גולן", en: "Eyal Golan", category: "singer" },
  { word: "נועה קירל", en: "Noa Kirel", category: "singer" },
  { word: "עומר אדם", en: "Omer Adam", category: "singer" },
  { word: "אריק איינשטיין", en: "Arik Einstein", category: "singer" },
  { word: "ביונסה", en: "Beyonce", category: "singer" },
  { word: "מייקל ג'קסון", en: "Michael Jackson", category: "singer" },
  { word: "מדונה", en: "Madonna", category: "singer" },
  { word: "טיילור סוויפט", en: "Taylor Swift", category: "singer" },
  { word: "אדל", en: "Adele", category: "singer" },
  { word: "חנן בן ארי", en: "Hanan Ben Ari", category: "singer" },
  { word: "עדן חסון", en: "Eden Hason", category: "singer" },
  { word: "ברי סחרוף", en: "Berry Sakharof", category: "singer" },
  { word: "זהר ארגוב", en: "Zohar Argov", category: "singer" },
  { word: "עדן בן זקן", en: "Eden Ben Zaken", category: "singer" },
  { word: "סטטיק", en: "Static", category: "singer" },
  { word: "בן אל תבורי", en: "Ben El Tavori", category: "singer" },
  { word: "מרגי", en: "Mergi", category: "singer" },
  { word: "ריטה", en: "Rita", category: "singer" },
  { word: "רמי קלינשטיין", en: "Rami Kleinstein", category: "singer" },
  { word: "אביב גפן", en: "Aviv Geffen", category: "singer" },
  { word: "נינט טייב", en: "Ninet Tayeb", category: "singer" },
  { word: "עידן רייכל", en: "Idan Raichel", category: "singer" },
  { word: "עברי לידר", en: "Ivri Lider", category: "singer" },
  { word: "ריקי גל", en: "Riki Gal", category: "singer" },
  { word: "יהודית רביץ", en: "Yehudit Ravitz", category: "singer" },
  { word: "גידי גוב", en: "Gidi Gov", category: "singer" },
  { word: "דני סנדרסון", en: "Danny Sanderson", category: "singer" },
  { word: "חוה אלברשטיין", en: "Chava Alberstein", category: "singer" },
  { word: "ירדנה ארזי", en: "Yardena Arazi", category: "singer" },
  { word: "עפרה חזה", en: "Ofra Haza", category: "singer" },
  { word: "זהבה בן", en: "Zehava Ben", category: "singer" },
  { word: "שרית חדד", en: "Sarit Hadad", category: "singer" },
  { word: "משה פרץ", en: "Moshe Peretz", category: "singer" },
  { word: "דודו אהרון", en: "Dudu Aharon", category: "singer" },
  { word: "ליאור נרקיס", en: "Lior Narkis", category: "singer" },
  { word: "קובי פרץ", en: "Kobi Peretz", category: "singer" },
  { word: "איתי לוי", en: "Itay Levi", category: "singer" },
  { word: "אושר כהן", en: "Osher Cohen", category: "singer" },
  { word: "ששון איפרם שאולוב", en: "Sasson Shaulov", category: "singer" },
  { word: "יסמין מועלם", en: "Jasmin Moallem", category: "singer" },
  { word: "נגה ארז", en: "Noga Erez", category: "singer" },
  { word: "אנה זק", en: "Anna Zak", category: "singer" },
  { word: "רן דנקר", en: "Ran Danker", category: "singer" },
  { word: "הראל סקעת", en: "Harel Skaat", category: "singer" },
  { word: "שירי מימון", en: "Shiri Maimon", category: "singer" },
  { word: "מארינה מקסימיליאן", en: "Marina Maximilian", category: "singer" },
  { word: "יובל דיין", en: "Yuval Dayan", category: "singer" },
  { word: "נתן גושן", en: "Natan Goshen", category: "singer" },
  { word: "אליעד נחום", en: "Eliad", category: "singer" },
  { word: "אברהם טל", en: "Avraham Tal", category: "singer" },
  { word: "מוש בן ארי", en: "Mosh Ben Ari", category: "singer" },
  { word: "מוקי", en: "Muki", category: "singer" },
  { word: "מוש בן ארי", en: "Mosh Ben Ari", category: "singer" },
  { word: "ג'סטין ביבר", en: "Justin Bieber", category: "singer" },
  { word: "אריאנה גרנדה", en: "Ariana Grande", category: "singer" },
  { word: "ריהאנה", en: "Rihanna", category: "singer" },
  { word: "דרייק", en: "Drake", category: "singer" },
  { word: "קניה ווסט", en: "Kanye West", category: "singer" },
  { word: "אמינם", en: "Eminem", category: "singer" },
  { word: "ליידי גאגא", en: "Lady Gaga", category: "singer" },
  { word: "ברונו מארס", en: "Bruno Mars", category: "singer" },
  { word: "בילי אייליש", en: "Billie Eilish", category: "singer" },
  { word: "פרדי מרקורי", en: "Freddie Mercury", category: "singer" },
  { word: "אלביס פרסלי", en: "Elvis Presley", category: "singer" },
  { word: "מייקל בובלה", en: "Michael Buble", category: "singer" },
  { word: "פרנק סינטרה", en: "Frank Sinatra", category: "singer" },
  { word: "בוב מארלי", en: "Bob Marley", category: "singer" },
  { word: "ג'ון לנון", en: "John Lennon", category: "singer" },
  { word: "פול מקרטני", en: "Paul McCartney", category: "singer" },
  { word: "מיק ג'אגר", en: "Mick Jagger", category: "singer" },
  { word: "דיוויד בואי", en: "David Bowie", category: "singer" },
  { word: "אלטון ג'ון", en: "Elton John", category: "singer" },
  { word: "סטיבי וונדר", en: "Stevie Wonder", category: "singer" },
  { word: "מייקל סטייפ", en: "Michael Stipe", category: "singer" },
  { word: "בונו", en: "Bono", category: "singer" },
  { word: "אקסל רוז", en: "Axl Rose", category: "singer" },
  { word: "קורט קוביין", en: "Kurt Cobain", category: "singer" },
  { word: "איימי ויינהאוס", en: "Amy Winehouse", category: "singer" },
  { word: "וויטני יוסטון", en: "Whitney Houston", category: "singer" },
  { word: "סלין דיון", en: "Celine Dion", category: "singer" },
  { word: "מריה קארי", en: "Mariah Carey", category: "singer" },
  { word: "ג'ניפר לופז", en: "Jennifer Lopez", category: "singer" },
  { word: "שאקירה", en: "Shakira", category: "singer" },
  { word: "בריטני ספירס", en: "Britney Spears", category: "singer" },
  { word: "כריסטינה אגילרה", en: "Christina Aguilera", category: "singer" },
  { word: "פינק", en: "Pink", category: "singer" },
  { word: "קייטי פרי", category: "singer" },

  // --- 2. שחקנים ושחקניות (actor) ---
  { word: "גל גדות", en: "Gal Gadot", category: "actor" },
  { word: "בראד פיט", en: "Brad Pitt", category: "actor" },
  { word: "לאונרדו דיקפריו", en: "Leonardo DiCaprio", category: "actor" },
  { word: "מריל סטריפ", en: "Meryl Streep", category: "actor" },
  { word: "איילת זורר", en: "Ayelet Zurer", category: "actor" },
  { word: "טום קרוז", en: "Tom Cruise", category: "actor" },
  { word: "ג'וני דפ", en: "Johnny Depp", category: "actor" },
  { word: "אנג'לינה ג'ולי", en: "Angelina Jolie", category: "actor" },
  { word: "ג'ניפר אניסטון", en: "Jennifer Aniston", category: "actor" },
  { word: "ויל סמית'", en: "Will Smith", category: "actor" },
  { word: "מורגן פרימן", en: "Morgan Freeman", category: "actor" },
  { word: "רוברט דה נירו", en: "Robert De Niro", category: "actor" },
  { word: "אל פצ'ינו", en: "Al Pacino", category: "actor" },
  { word: "טום הנקס", en: "Tom Hanks", category: "actor" },
  { word: "ג'וליה רוברטס", en: "Julia Roberts", category: "actor" },
  { word: "סקרלט ג'והנסון", en: "Scarlett Johansson", category: "actor" },
  { word: "דוויין ג'ונסון", en: "Dwayne Johnson", category: "actor" },
  { word: "מרגו רובי", en: "Margot Robbie", category: "actor" },
  { word: "ראיין גוסלינג", en: "Ryan Gosling", category: "actor" },
  { word: "אמה סטון", en: "Emma Stone", category: "actor" },
  { word: "נטלי פורטמן", en: "Natalie Portman", category: "actor" },
  { word: "שירה האס", en: "Shira Haas", category: "actor" },
  { word: "ליאור אשכנזי", en: "Lior Ashkenazi", category: "actor" },
  { word: "יהודה לוי", en: "Yehuda Levi", category: "actor" },
  { word: "אביב אלוש", en: "Aviv Alush", category: "actor" },
  { word: "נועה תשבי", en: "Noa Tishby", category: "actor" },
  { word: "אדווה דדון", en: "Adva Dadon", category: "actor" },
  { word: "צחי הלוי", en: "Tsahi Halevi", category: "actor" },
  { word: "איתי טיראן", en: "Itay Tiran", category: "actor" },
  { word: "אסי כהן", en: "Assi Cohen", category: "actor" },
  { word: "שלום מיכאלשווילי", en: "Shalom Michaelshwilli", category: "actor" },
  { word: "ציון ברוך", en: "Zion Baruch", category: "actor" },
  { word: "אסי ישראלוף", en: "Assi Israelof", category: "actor" },
  { word: "עדי אשכנזי", en: "Adi Ashkenazi", category: "actor" },
  { word: "רותם סלע", en: "Rotem Sela", category: "actor" },
  { word: "אסי עזר", en: "Assi Azar", category: "actor" },
  { word: "גיא זוארץ", en: "Guy Zu-Aretz", category: "actor" },
  { word: "ליאור רז", en: "Lior Raz", category: "actor" },
  { word: "מיכאל אלוני", en: "Michael Aloni", category: "actor" },
  { word: "עוז זהבי", en: "Oz Zehavi", category: "actor" },

  // --- 3. כדורגלנים (footballer) ---
  { word: "ליאו מסי", en: "Lionel Messi", category: "footballer" },
  { word: "כריסטיאנו רונאלדו", en: "Cristiano Ronaldo", category: "footballer" },
  { word: "קיליאן אמבפה", en: "Kylian Mbappe", category: "footballer" },
  { word: "ארלינג הולאנד", en: "Erling Haaland", category: "footballer" },
  { word: "ערן זהבי", en: "Eran Zahavi", category: "footballer" },
  { word: "מנור סולומון", en: "Manor Solomon", category: "footballer" },
  { word: "יוסי בניון", en: "Yossi Benayoun", category: "footballer" },
  { word: "אלי אוחנה", en: "Eli Ohana", category: "footballer" },
  { word: "אורי מלמיליאן", en: "Uri Malmilian", category: "footballer" },
  { word: "דייוויד בקהאם", en: "David Beckham", category: "footballer" },
  { word: "זינדין זידאן", en: "Zinedine Zidane", category: "footballer" },
  { word: "רונאלדיניו", en: "Ronaldinho", category: "footballer" },
  { word: "פלה", en: "Pele", category: "footballer" },
  { word: "דייגו מראדונה", en: "Diego Maradona", category: "footballer" },
  { word: "ניימאר", en: "Neymar", category: "footballer" },
  { word: "מוחמד סלאח", en: "Mohamed Salah", category: "footballer" },
  { word: "הארי קיין", en: "Harry Kane", category: "footballer" },
  { word: "לואיס סוארס", en: "Luis Suarez", category: "footballer" },
  { word: "קארים בנזמה", en: "Karim Benzema", category: "footballer" },
  { word: "לוקה מודריץ'", en: "Luka Modric", category: "footballer" },
  { word: "רוברט לבנדובסקי", en: "Robert Lewandowski", category: "footballer" },
  { word: "זלאטן איברהימוביץ'", en: "Zlatan Ibrahimovic", category: "footballer" },
  { word: "דניאל פרץ", en: "Daniel Peretz", category: "footballer" },
  { word: "אוסקר גלוך", en: "Oscar Gloukh", category: "footballer" },

  // --- 4. פוליטיקאים וראשי מדינה (head_of_state / politician) ---
  { word: "בנימין נתניהו", en: "Benjamin Netanyahu", category: "head_of_state" },
  { word: "יצחק רבין", en: "Yitzhak Rabin", category: "head_of_state" },
  { word: "דוד בן גוריון", en: "David Ben Gurion", category: "head_of_state" },
  { word: "גולדה מאיר", en: "Golda Meir", category: "head_of_state" },
  { word: "מנחם בגין", en: "Menachem Begin", category: "head_of_state" },
  { word: "שמעון פרס", en: "Shimon Peres", category: "head_of_state" },
  { word: "ברק אובמה", en: "Barack Obama", category: "head_of_state" },
  { word: "דונלד טראמפ", en: "Donald Trump", category: "head_of_state" },
  { word: "ג'ו ביידן", en: "Joe Biden", category: "head_of_state" },
  { word: "ולדימיר פוטין", en: "Vladimir Putin", category: "head_of_state" },
  { word: "עמנואל מקרון", en: "Emmanuel Macron", category: "head_of_state" },
  { word: "בוריס ג'ונסון", en: "Boris Johnson", category: "head_of_state" },
  { word: "אנגלה מרקל", en: "Angela Merkel", category: "head_of_state" },
  { word: "ווינסטון צ'רצ'יל", en: "Winston Churchill", category: "head_of_state" },
  { word: "אברהם לינקולן", en: "Abraham Lincoln", category: "head_of_state" },
  { word: "נלסון מנדלה", en: "Nelson Mandela", category: "head_of_state" },
  { word: "יאיר לפיד", en: "Yair Lapid", category: "politician" },
  { word: "בני גנץ", en: "Benny Gantz", category: "politician" },
  { word: "אביגדור ליברמן", en: "Avigdor Lieberman", category: "politician" },
  { word: "אריה דרעי", en: "Aryeh Deri", category: "politician" },
  { word: "איתמר בן גביר", en: "Itamar Ben Gvir", category: "politician" },
  { word: "בצלאל סמוטריץ'", en: "Bezalel Smotrich", category: "politician" },
  { word: "מרב מיכאלי", en: "Merav Michaeli", category: "politician" },

  // --- [כאן מגיעים עוד כ-600 שמות נוספים מהרשימה המקורית שאושרה] ---
  // (מפאת קוצר המקום בתשובה אחת, צירפתי את הקטגוריות הראשיות. 
  // האם תרצה שאשלח את המשך הרשימה בחלקים כדי לוודא ששום דבר לא הולך לאיבוד?)

  { word: "אלברט איינשטיין", en: "Albert Einstein", category: "thinker" },
  { word: "סטיב ג'ובס", en: "Steve Jobs", category: "entrepreneur" },
  { word: "אילון מאסק", en: "Elon Musk", category: "entrepreneur" },
  { word: "ביל גייטס", en: "Bill Gates", category: "entrepreneur" },
  { word: "מארק צוקרברג", en: "Mark Zuckerberg", category: "entrepreneur" },
  { word: "ג'ף בזוס", en: "Jeff Bezos", category: "entrepreneur" },
  { word: "וולט דיסני", en: "Walt Disney", category: "entrepreneur" },
  { word: "סטיבן ספילברג", en: "Steven Spielberg", category: "director" },
  { word: "וולטר ווייט", en: "Walter White", category: "tv_character" },
  { word: "הומר סימפסון", en: "Homer Simpson", category: "cartoon_character" },
  { word: "באטמן", en: "Batman", category: "superhero" },
  { word: "ספיידרמן", en: "Spider-Man", category: "superhero" },
// --- המשך רשימת ספורטאים (ספורט עולמי וישראלי) ---
{ word: "נובאק ג'וקוביץ'", en: "Novak Djokovic", category: "tennis_player" },
{ word: "רפאל נדאל", en: "Rafael Nadal", category: "tennis_player" },
{ word: "סטפן קרי", en: "Stephen Curry", category: "basketballer" },
{ word: "קובי בראיינט", en: "Kobe Bryant", category: "basketballer" },
{ word: "שאקיל אוניל", en: "Shaquille O'Neal", category: "basketballer" },
{ word: "עומרי כספי", en: "Omri Casspi", category: "basketballer" },
{ word: "מיקי ברקוביץ'", en: "Miki Berkovich", category: "basketballer" },
{ word: "דורון ג'מצ'י", en: "Doron Jamchi", category: "basketballer" },
{ word: "טל ברודי", en: "Tal Brody", category: "basketballer" },
{ word: "ים מדר", en: "Yam Madar", category: "basketballer" },
{ word: "טייגר וודס", en: "Tiger Woods", category: "olympic_athlete" },
{ word: "סימון ביילס", en: "Simone Biles", category: "olympic_athlete" },
{ word: "ארטיום דולגופיאט", en: "Artem Dolgopyat", category: "olympic_athlete" },
{ word: "אריק זאבי", en: "Ariel Zeevi", category: "olympic_athlete" },
{ word: "יעל ארד", en: "Yael Arad", category: "olympic_athlete" },
{ word: "אורי ששון", en: "Ori Sasson", category: "olympic_athlete" },
{ word: "שגיא מוקי", en: "Sagi Muki", category: "olympic_athlete" },

// --- אנשי עסקים וטכנולוגיה (entrepreneur) ---
{ word: "וורן באפט", en: "Warren Buffett", category: "entrepreneur" },
{ word: "ריצ'רד ברנסון", en: "Richard Branson", category: "entrepreneur" },
{ word: "סטף ורטהיימר", en: "Stef Wertheimer", category: "entrepreneur" },
{ word: "שרי אריסון", en: "Shari Arison", category: "entrepreneur" },
{ word: "יצחק תשובה", en: "Yitzhak Tshuva" , category: "entrepreneur" },
{ word: "עידן עופר", en: "Idan Ofer", category: "entrepreneur" },
{ word: "רמי לוי", en: "Rami Levy", category: "entrepreneur" },

// --- דמויות היסטוריות ותרבות (historical / thinker) ---
{ word: "מרקו פולו", en: "Marco Polo", category: "historical_figure" },
{ word: "כריסטופר קולומבוס", en: "Christopher Columbus", category: "historical_figure" },
{ word: "ניל ארמסטרונג", en: "Neil Armstrong", category: "historical_figure" },
{ word: "מרי קירי", en: "Marie Curie", category: "thinker" },
{ word: "צ'ארלס דרווין", en: "Charles Darwin", category: "thinker" },
{ word: "גלילאו גליליי", en: "Galileo Galilei", category: "thinker" },
{ word: "סוקרטס", en: "Socrates", category: "thinker" },
{ word: "אריסטו", en: "Aristotle", category: "thinker" },
{ word: "אפלטון", en: "Plato", category: "thinker" },
{ word: "מהטמה גנדי", en: "Mahatma Gandhi", category: "historical_figure" },
{ word: "מרטין לותר", en: "Martin Luther", category: "historical_figure" },

// --- דמויות טלוויזיה ובידור ישראלי (tv_character / journalist) ---
{ word: "ארז טל", en: "Erez Tal", category: "journalist" },
{ word: "אברי גלעד", en: "Avri Gilad", category: "journalist" },
{ word: "צביקה הדר", en: "Zvika Hadar", category: "actor" },
{ word: "מירי מסיקה", en: "Miri Mesika", category: "singer" },
{ word: "קרן פלס", en: "Keren Peles", category: "singer" },
{ word: "שירי מימון", en: "Shiri Maimon", category: "singer" },
{ word: "אבי קושניר", en: "Avi Kushnir", category: "actor" },
{ word: "מוני מושונוב", en: "Moni Moshonov", category: "actor" },
{ word: "שלמה בראבא", en: "Shlomo Baraba", category: "actor" },
{ word: "דב נבון", en: "Dov Navon", category: "actor" },
{ word: "קרן מור", en: "Keren Mor", category: "actor" },
{ word: "אילנה דיין", en: "Ilana Dayan", category: "journalist" },
{ word: "רפי רשף", en: "Rafi Reshef", category: "journalist" },
{ word: "עודד בן עמי", en: "Oded Ben-Ami", category: "journalist" },
{ word: "אמנון לוי", en: "Amnon Levi", category: "journalist" },
{ word: "חיים אתגר", en: "Haim Etgar", category: "journalist" },
{ word: "ניב רסקין", en: "Niv Raskin", category: "journalist" },

// --- המשך דמויות טלוויזיה, בידור וקומדיה (actor / tv_character) ---
{ word: "אדיר מילר", en: "Adir Miller", category: "actor" },
{ word: "ליטל שוורץ", en: "Lital Schwartz", category: "actor" },
{ word: "ישראל קטורזה", en: "Israel Katorza", category: "actor" },
{ word: "אלי פיניש", en: "Eli Finish", category: "actor" },
{ word: "מריאנו אידלמן", en: "Mariano Idelman", category: "actor" },
{ word: "עלמה זק", en: "Alma Zack", category: "actor" },
{ word: "שני כהן", en: "Shani Cohen", category: "actor" },
{ word: "ליאת הר לב", en: "Liat Har Lev", category: "actor" },
{ word: "יניב ביטון", en: "Yaniv Biton", category: "actor" },
{ word: "ערן זרחוביץ'", en: "Eran Zarahovitsh", category: "actor" },
{ word: "מאור כהן", en: "Maor Cohen", category: "actor" },
{ word: "טל פרידמן", en: "Tal Friedman", category: "actor" },
{ word: "איל קיציס", en: "Eyal Kitzis", category: "actor" },
{ word: "יובל סמו", en: "Yuval Semo", category: "actor" },
{ word: "רועי בר נתן", en: "Roey Bar-Natan", category: "actor" },
{ word: "אילן פלד", en: "Ilan Peled", category: "actor" },
{ word: "יעקב כהן", en: "Yaakov Cohen", category: "actor" },
{ word: "צחי נוי", en: "Zachi Noy", category: "actor" },
{ word: "יהודה בארקן", en: "Yehuda Barkan", category: "actor" },
{ word: "זאב רווח", en: "Zeev Revach", category: "actor" },
{ word: "טוביה צפיר", en: "Tuvia Tzafir", category: "actor" },
{ word: "ספי ריבלין", en: "Sefi Rivlin", category: "actor" },
{ word: "דודו טופז", en: "Dudu Topaz", category: "actor" },

// --- דמויות מהוליווד וקולנוע עולמי (actor) ---
{ word: "דנזל וושינגטון", en: "Denzel Washington", category: "actor" },
{ word: "ניקול קידמן", en: "Nicole Kidman", category: "actor" },
{ word: "קייט וינסלט", en: "Kate Winslet", category: "actor" },
{ word: "סנדרה בולוק", en: "Sandra Bullock", category: "actor" },
{ word: "הריסון פורד", en: "Harrison Ford", category: "actor" },
{ word: "סילבסטר סטאלון", en: "Sylvester Stallone", category: "actor" },
{ word: "ארנולד שוורצנגר", en: "Arnold Schwarzenegger", category: "actor" },
{ word: "ג'ק ניקולסון", en: "Jack Nicholson", category: "actor" },
{ word: "אנתוני הופקינס", en: "Anthony Hopkins" , category: "actor" },
{ word: "נטלי פורטמן", en: "Natalie Portman", category: "actor" },
{ word: "קיאנו ריבס", en: "Keanu Reeves", category: "actor" },
{ word: "יו גרנט", en: "Hugh Grant", category: "actor" },
{ word: "ג'ורג' קלוני", en: "George Clooney", category: "actor" },
{ word: "בן אפלק", en: "Ben Affleck", category: "actor" },
{ word: "מאט דיימון", en: "Matt Damon", category: "actor" },
{ word: "ג'ייסון סטיית'ם", en: "Jason Statham", category: "actor" },
{ word: "וין דיזל", en: "Vin Diesel", category: "actor" },
{ word: "מארק וולברג", en: "Mark Wahlberg", category: "actor" },
{ word: "ריאן ריינולדס", en: "Ryan Reynolds", category: "actor" },
{ word: "כריס המסוורת'", en: "Chris Hemsworth", category: "actor" },
{ word: "טום הרדי", en: "Tom Hardy", category: "actor" },

// --- דמויות היסטוריות ומנהיגים בעולם (historical_figure / head_of_state) ---
{ word: "מהטמה גנדי", en: "Mahatma Gandhi", category: "historical_figure" },
{ word: "מרטין לותר קינג", en: "Martin Luther King Jr.", category: "historical_figure" },
{ word: "נלסון מנדלה", en: "Nelson Mandela", category: "historical_figure" },
{ word: "ג'ון פ. קנדי", en: "John F. Kennedy", category: "head_of_state" },
{ word: "מרגרט תאצ'ר", en: "Margaret Thatcher", category: "head_of_state" },
{ word: "אינדירה גנדי", en: "Indira Gandhi", category: "head_of_state" },
{ word: "פידל קסטרו", en: "Fidel Castro", category: "head_of_state" },
{ word: "צ'ה גווארה", en: "Che Guevara", category: "historical_figure" },
{ word: "יצחק שמיר", en: "Yitzhak Shamir", category: "head_of_state" },
{ word: "עזר ויצמן", en: "Ezer Weizman", category: "head_of_state" },
{ word: "חיים ויצמן", en: "Chaim Weizmann", category: "head_of_state" },
{ word: "תיאודור הרצל", en: "Theodor Herzl", category: "historical_figure" },
{ word: "זאב ז'בוטינסקי", en: "Ze'ev Jabotinsky", category: "historical_figure" },

// --- דמויות מעולם הילדים והאנימציה (cartoon_character / superhero) ---
{ word: "סופרמן", en: "Superman", category: "superhero" },
{ word: "איירון מן", en: "Iron Man", category: "superhero" },
{ word: "קפטן אמריקה", en: "Captain America", category: "superhero" },
{ word: "הענק הירוק", en: "Hulk", category: "superhero" },
{ word: "תור (מארוול)", en: "Thor", category: "superhero" },
{ word: "בובספוג", en: "SpongeBob SquarePants", category: "cartoon_character" },
{ word: "פטריק (בובספוג)", en: "Patrick Star", category: "cartoon_character" },
{ word: "דונלד דאק", en: "Donald Duck", category: "cartoon_character" },
{ word: "באגס באני", en: "Bugs Bunny", category: "cartoon_character" },
{ word: "פו הדב", en: "Winnie the Pooh", category: "cartoon_character" },
{ word: "אלזה (לשבור את הקרח)", en: "Elsa", category: "cartoon_character" },
{ word: "סימבה (מלך האריות)", en: "Simba", category: "cartoon_character" },

// --- דמויות נוספות מהתרבות הפופולרית, ספורט והיסטוריה ---
{ word: "ג'יימס בונד", en: "James Bond", category: "movie_character" },
{ word: "שרלוק הולמס", en: "Sherlock Holmes", category: "movie_character" },
{ word: "אלבוס דמבלדור", en: "Albus Dumbledore", category: "movie_character" },
{ word: "וולדמורט", en: "Voldemort", category: "movie_character" },
{ word: "קאטניס אוורדין", en: "Katniss Everdeen", category: "movie_character" },
{ word: "פורסט גאמפ", en: "Forrest Gump", category: "movie_character" },
{ word: "רוקי בלבואה", en: "Rocky Balboa", category: "movie_character" },
{ word: "שרה קונור", en: "Sarah Connor", category: "movie_character" },
{ word: "מר וולף (ספרות זולה)", en: "The Wolf", category: "movie_character" },
{ word: "טיילר דרדן (מועדון קרב)", en: "Tyler Durden", category: "movie_character" },

// --- ספורטאים נוספים (עבר והווה) ---
{ word: "קובי בראיינט", en: "Kobe Bryant", category: "basketballer" },
{ word: "קארים עבדול-ג'באר", en: "Kareem Abdul-Jabbar", category: "basketballer" },
{ word: "שאקיל אוניל", en: "Shaquille O'Neal", category: "basketballer" },
{ word: "מג'יק ג'ונסון", en: "Magic Johnson", category: "basketballer" },
{ word: "לארי בירד", en: "Larry Bird", category: "basketballer" },
{ word: "דיאגו סימאונה", en: "Diego Simeone", category: "footballer" },
{ word: "פפ גווארדיולה", en: "Pep Guardiola", category: "footballer" },
{ word: "יורגן קלופ", en: "Jurgen Klopp", category: "footballer" },
{ word: "אלכס פרגוסון", en: "Alex Ferguson", category: "footballer" },
{ word: "מיכאל שומאכר", en: "Michael Schumacher", category: "racing_driver" },
{ word: "לואיס המילטון", en: "Lewis Hamilton", category: "racing_driver" },
{ word: "איירטון סנה", en: "Ayrton Senna", category: "racing_driver" },

// --- מנהיגים ודמויות ישראליות (עבר והווה) ---
{ word: "לוי אשכול", en: "Levi Eshkol", category: "head_of_state" },
{ word: "משה שרת", en: "Moshe Sharett", category: "head_of_state" },
{ word: "פנחס ספיר", en: "Pinhas Sapir", category: "politician" },
{ word: "גאולה כהן", en: "Geula Cohen", category: "politician" },
{ word: "שולמית אלוני", en: "Shulamit Aloni", category: "politician" },
{ word: "יוסי שריד", en: "Yossi Sarid", category: "politician" },
{ word: "רפאל איתן (רפול)", en: "Rafael Eitan", category: "historical_figure" },
{ word: "חיים בר-לב", en: "Haim Bar-Lev", category: "historical_figure" },
{ word: "מרדכי גור (מוטה)", en: "Mordechai Gur", category: "historical_figure" },
{ word: "דן חלוץ", en: "Dan Halutz", category: "historical_figure" },
{ word: "גבי אשכנזי", en: "Gabi Ashkenazi", category: "historical_figure" },
{ word: "אביב כוכבי", en: "Aviv Kochavi", category: "historical_figure" },
{ word: "הרצי הלוי", en: "Herzi Halevi", category: "historical_figure" },

// --- מדענים, הוגים ואנשי רוח ---
{ word: "ניקולה טסלה", en: "Nikola Tesla", category: "thinker" },
{ word: "מארי קירי", en: "Marie Curie", category: "thinker" },
{ word: "סטיבן הוקינג", en: "Stephen Hawking", category: "thinker" },
{ word: "פרידריך ניטשה", en: "Friedrich Nietzsche", category: "thinker" },
{ word: "רנה דקארט", en: "Rene Descartes", category: "thinker" },
{ word: "עמנואל קאנט", en: "Immanuel Kant", category: "thinker" },
{ word: "קרל מרקס", en: "Karl Marx", category: "thinker" },
{ word: "ז'אן ז'אק רוסו", en: "Jean-Jacques Rousseau", category: "thinker" },

// --- דמויות מהתנ"ך והיסטוריה יהודית ---
{ word: "אברהם אבינו", en: "Abraham", category: "biblical" },
{ word: "יצחק אבינו", en: "Isaac", category: "biblical" },
{ word: "יעקב אבינו", en: "Jacob", category: "biblical" },
{ word: "רחל אמנו", en: "Rachel", category: "biblical" },
{ word: "לאה אמנו", en: "Leah", category: "biblical" },
{ word: "יוסף הצדיק", en: "Joseph", category: "biblical" },
{ word: "יהושע בן נון", en: "Joshua", category: "biblical" },
{ word: "שלמה המלך", en: "King Solomon", category: "biblical" },
{ word: "מרדכי היהודי", en: "Mordechai", category: "biblical" },
{ word: "אסתר המלכה", en: "Queen Esther", category: "biblical" },
{ word: "יהודה המכבי", en: "Judah Maccabee", category: "biblical" },
{ word: "בר כוכבא", en: "Bar Kokhba", category: "historical_figure" },
{ word: "רש\"י", en: "Rashi", category: "thinker" },
{ word: "הרמב\"ם", en: "Maimonides", category: "thinker" }
];



