import { WordItem } from "../../game.config";

export const JUNIOR_WORDS: WordItem[] = [
  // --- המאגר הקיים ---
  { word: "מזגן", en: "Air Conditioner", img: "/words/junior/air_conditioner.webp" },
  { word: "מטוס", en: "Airplane", img: "/words/junior/airplane.webp" },
  { word: "שעון מעורר", en: "Alarm Clock", img: "/words/junior/alarm_clock.webp" },
  { word: "פוטבול אמריקאי", en: "American Football", img: "/words/junior/american_football.webp" },
  { word: "נמלה", en: "Ant", img: "/words/junior/ant.webp" },
  { word: "בניין מגורים", en: "Apartment Building", img: "/words/junior/apartment_building.webp" },
  { word: "תפוח", en: "Apple", img: "/words/junior/apple.webp" },
  { word: "קליעה למטרה", en: "Archery", img: "/words/junior/archery.webp" },
  { word: "אסטרונאוט", en: "Astronaut", img: "/words/junior/astronaut.webp" },
  { word: "בייגל", en: "Bagel", img: "/words/junior/bagel.webp" },
  { word: "בלט", en: "Ballet", img: "/words/junior/ballet.webp" },
  { word: "בננה", en: "Banana", img: "/words/junior/banana.webp" },
  { word: "שטרות", en: "Banknotes", img: "/words/junior/banknotes.webp" },
  { word: "כדורסל", en: "Basketball", img: "/words/junior/basketball.webp" },
  { word: "עטלף", en: "Bat", img: "/words/junior/bat.webp" },
  { word: "סוללה", en: "Battery", img: "/words/junior/battery.webp" },
  { word: "דבורה", en: "Bee", img: "/words/junior/bee.webp" },
  { word: "חגורה", en: "Belt", img: "/words/junior/belt.webp" },
  { word: "אופניים", en: "Bicycle", img: "/words/junior/bicycle.webp" },
  { word: "לוח", en: "Board", img: "/words/junior/board.webp" },
  { word: "סירה", en: "Boat", img: "/words/junior/boat.webp" },
  { word: "מדף ספרים", en: "Bookshelf", img: "/words/junior/books_shelf.webp" },
  { word: "מגפיים", en: "Boots", img: "/words/junior/boots.webp" },
  { word: "עניבת פרפר", en: "Bow Tie", img: "/words/junior/bow_tie.webp" },
  { word: "באולינג", en: "Bowling", img: "/words/junior/bowling.webp" },
  { word: "איגרוף", en: "Boxing", img: "/words/junior/boxing.webp" },
  { word: "גשר", en: "Bridge", img: "/words/junior/bridge.webp" },
  { word: "באפלו", en: "Buffalo", img: "/words/junior/buffalo.webp" },
  { word: "דחפור", en: "Bulldozer", img: "/words/junior/bulldozer.webp" },
  { word: "בוריטו", en: "Burrito", img: "/words/junior/burrito.webp" },
  { word: "אוטובוס", en: "Bus", img: "/words/junior/bus.webp" },
  { word: "כבל", en: "Cable", img: "/words/junior/cable.webp" },
  { word: "עוגה", en: "Cake", img: "/words/junior/cake.webp" },
  { word: "מחשבון", en: "Calculator", img: "/words/junior/calculator.webp" },
  { word: "מצלמה", en: "Camera", img: "/words/junior/camera.webp" },
  { word: "גמל", en: "Camel", img: "/words/junior/camel.webp" },
  { word: "נר", en: "Candle", img: "/words/junior/candle.webp" },
  { word: "קרקל", en: "Caracal", img: "/words/junior/caracal.webp" },
  { word: "טירה", en: "Castle", img: "/words/junior/castle.webp" },
  { word: "צ'לו", en: "Cello", img: "/words/junior/cello.webp" },
  { word: "זיקית", en: "Chameleon", img: "/words/junior/chameleon.webp" },
  { word: "גבינה", en: "Cheese", img: "/words/junior/cheese.webp" },
  { word: "ברדלס", en: "Cheetah", img: "/words/junior/cheetah.webp" },
  { word: "שחמט", en: "Chess", img: "/words/junior/chess.webp" },
  { word: "שימפנזה", en: "Chimpanzee", img: "/words/junior/chimpanzee.webp" },
  { word: "שוקולד", en: "Chocolate", img: "/words/junior/chocolate.webp" },
  { word: "קוברה", en: "Cobra", img: "/words/junior/cobra.webp" },
  { word: "מטבעות", en: "Coins", img: "/words/junior/coins.webp" },
  { word: "מצפן", en: "Compass", img: "/words/junior/compass.webp" },
  { word: "מנוף", en: "Crane", img: "/words/junior/crane.webp" },
  { word: "תנין", en: "Crocodile", img: "/words/junior/crocodile.webp" },
  { word: "רכיבה על אופניים", en: "Cycling", img: "/words/junior/cycling.webp" },
  { word: "רקדנית", en: "Dancer", img: "/words/junior/dancer.webp" },
  { word: "אייל", en: "Deer", img: "/words/junior/deer.webp" },
  { word: "רופא שיניים", en: "Dentist", img: "/words/junior/dentist.webp" },
  { word: "מדבר", en: "Desert", img: "/words/junior/desert.webp" },
  { word: "צוללן", en: "Diver", img: "/words/junior/diver.webp" },
  { word: "דולפין", en: "Dolphin", img: "/words/junior/dolphin.webp" },
  { word: "דונאט", en: "Donut", img: "/words/junior/donut.webp" },
  { word: "מקדחה", en: "Drill", img: "/words/junior/drill.webp" },
  { word: "רחפן", en: "Drone", img: "/words/junior/drone.webp" },
  { word: "תופים", en: "Drums", img: "/words/junior/drums.webp" },
  { word: "עיט", en: "Eagle", img: "/words/junior/eagle.webp" },
  { word: "ביצה", en: "Egg", img: "/words/junior/egg.webp" },
  { word: "דרגנוע", en: "Escalator", img: "/words/junior/escalator.webp" },
  { word: "סייף", en: "Fencing", img: "/words/junior/fencing.webp" },
  { word: "כבאית", en: "Fire Truck", img: "/words/junior/fire_truck.webp" },
  { word: "כבאים", en: "Firefighter", img: "/words/junior/firefighter.webp" },
  { word: "זיקוקים", en: "Fireworks", img: "/words/junior/fireworks.webp" },
  { word: "דג", en: "Fish", img: "/words/junior/fish.webp" },
  { word: "פלמינגו", en: "Flamingo", img: "/words/junior/flamingo.webp" },
  { word: "כפכפים", en: "Flip-flops", img: "/words/junior/flip-flops.webp" },
  { word: "חליל", en: "Flute", img: "/words/junior/flute.webp" },
  { word: "יער", en: "Forest", img: "/words/junior/forest.webp" },
  { word: "שועל", en: "Fox", img: "/words/junior/fox.webp" },
  { word: "צ'יפס", en: "French Fries", img: "/words/junior/french_fries.webp" },
  { word: "מקרר", en: "Fridge", img: "/words/junior/fridge.webp" },
  { word: "צפרדע", en: "Frog", img: "/words/junior/frog.webp" },
  { word: "צינור גינה", en: "Garden Hose", img: "/words/junior/garden_hose.webp" },
  { word: "מתנה", en: "Gift", img: "/words/junior/gift.webp" },
  { word: "ילדה", en: "Girl", img: "/words/junior/girl.webp" },
  { word: "גלובוס", en: "Globe", img: "/words/junior/globe.webp" },
  { word: "גולף", en: "Golf", img: "/words/junior/golf.webp" },
  { word: "גורילה", en: "Gorilla", img: "/words/junior/gorilla.webp" },
  { word: "ענבים", en: "Grape", img: "/words/junior/grape.webp" },
  { word: "גיטרה", en: "Guitar", img: "/words/junior/guitar.webp" },
  { word: "מברשת שיער", en: "Hairbrush", img: "/words/junior/hairbrush.webp" },
  { word: "פטיש", en: "Hammer", img: "/words/junior/hammer.webp" },
  { word: "יד", en: "Hand", img: "/words/junior/hand.webp" },
  { word: "תיק יד", en: "Handbag", img: "/words/junior/handbag.webp" },
  { word: "מפוחית", en: "Harp", img: "/words/junior/harp.webp" },
  { word: "קיפוד", en: "Hedgehog", img: "/words/junior/hedgehog.webp" },
  { word: "מסוק", en: "Helicopter", img: "/words/junior/helicopter.webp" },
  { word: "מרקר", en: "Highlighter", img: "/words/junior/highlighter.webp" },
  { word: "היפופוטם", en: "Hippopotamus", img: "/words/junior/hippopotamus.webp" },
  { word: "הוקי", en: "Hockey", img: "/words/junior/hockey.webp" },
  { word: "דבש", en: "Honey", img: "/words/junior/honey.webp" },
  { word: "סוס", en: "Horse", img: "/words/junior/horse.webp" },
  { word: "רכיבה על סוסים", en: "Horseback Riding", img: "/words/junior/horseback_riding.webp" },
  { word: "כדור פורח", en: "Hot Air Balloon", img: "/words/junior/hot_air_balloon.webp" },
  { word: "נקניקייה", en: "Hot Dog", img: "/words/junior/hot_dog.webp" },
  { word: "בתים", en: "Houses", img: "/words/junior/houses.webp" },
  { word: "חיבוק", en: "Hug", img: "/words/junior/hug.webp" },
  { word: "צבוע", en: "Hyena", img: "/words/junior/hyena.webp" },
  { word: "גלידה", en: "Ice Cream", img: "/words/junior/ice_cream.webp" },
  { word: "גביע גלידה", en: "Ice Cream Cone", img: "/words/junior/ice_cream_cone.webp" },
  { word: "מגהץ", en: "Iron", img: "/words/junior/iron.webp" },
  { word: "מדוזה", en: "Jellyfish", img: "/words/junior/jellyfish.webp" },
  { word: "מטוס סילון", en: "Jet", img: "/words/junior/jet.webp" },
  
  { word: "קנגורו", en: "Kangaroo", img: "/words/junior/kangaroo.webp" },
  { word: "קראטה", en: "Karate", img: "/words/junior/karate.webp" },
  { word: "קומקום", en: "Kettle", img: "/words/junior/kettle.webp" },
  { word: "מקלדת", en: "Keyboard", img: "/words/junior/keyboard.webp" },
  { word: "קיווי", en: "Kiwi", img: "/words/junior/kiwi.webp" },
  { word: "קואלה", en: "Koala", img: "/words/junior/koala.webp" },
  { word: "סולם", en: "Ladder", img: "/words/junior/ladder.webp" },
  { word: "חיפושית", en: "Ladybug", img: "/words/junior/ladybug.webp" },
  { word: "נורה", en: "Light Bulb", img: "/words/junior/light_bulb.webp" },
  { word: "מצתים", en: "Lighters", img: "/words/junior/lighters.webp" },
  { word: "ברק", en: "Lightning", img: "/words/junior/lightning.webp" },
  { word: "אריה", en: "Lion", img: "/words/junior/lion.webp" },
  { word: "למה", en: "Llama", img: "/words/junior/llama.webp" },
  { word: "מנעול", en: "Lock", img: "/words/junior/lock.webp" },
  { word: "זכוכית מגדלת", en: "Magnifying Glass", img: "/words/junior/magnifying_glass.webp" },
  { word: "גפרור", en: "Matchstick", img: "/words/junior/matchstick.webp" },
  { word: "מדליה", en: "Medal", img: "/words/junior/medal.webp" },
  { word: "מכונאי", en: "Mechanic", img: "/words/junior/mechanic.webp" },
  { word: "קוף", en: "Monkey", img: "/words/junior/monkey.webp" },
  { word: "אופנוע", en: "Motorcycle", img: "/words/junior/motorcycle.webp" },
  { word: "הר", en: "Mountain", img: "/words/junior/mountain.webp" },
  { word: "טיפוס הרים", en: "Mountain Climbing", img: "/words/junior/mountain_climbing.webp" },
  { word: "מאפין", en: "Muffin", img: "/words/junior/muffin.webp" },
  { word: "מנורת לילה", en: "Night Lamp", img: "/words/junior/night_lamp.webp" },
  { word: "תפוז", en: "Orange", img: "/words/junior/orange.webp" },
  { word: "יענים", en: "Ostrich", img: "/words/junior/ostrich.webp" },
  { word: "לוטרה", en: "Otter", img: "/words/junior/otter.webp" },
  { word: "ינשוף", en: "Owl", img: "/words/junior/owl.webp" },
  { word: "צייר", en: "Painter", img: "/words/junior/painter.webp" },
  { word: "פנקייק", en: "Pancake", img: "/words/junior/pancake.webp" },
  { word: "פנדה", en: "Panda", img: "/words/junior/panda.webp" },
  { word: "תוכי", en: "Parrot", img: "/words/junior/parrot.webp" },
  { word: "טווס", en: "Peacock", img: "/words/junior/peacock.webp" },
  { word: "עיפרון", en: "Pencil", img: "/words/junior/pencil.webp" },
  { word: "עפרונות", en: "Pencils", img: "/words/junior/pencils.webp" },
  { word: "פינגווין", en: "Penguin", img: "/words/junior/penguin.webp" },
  { word: "צלם", en: "Photographer", img: "/words/junior/photographer.webp" },
  { word: "פסנתר", en: "Piano", img: "/words/junior/piano.webp" },
  { word: "פאי", en: "Pie", img: "/words/junior/pie.webp" },
  { word: "אננס", en: "Pineapple", img: "/words/junior/pineapple.webp" },
  { word: "פיצה", en: "Pizza", img: "/words/junior/pizza.webp" },
  { word: "כדור הארץ", en: "Planet Earth", img: "/words/junior/planet_earth.webp" },
  { word: "פלייר", en: "Pliers", img: "/words/junior/pliers.webp" },
  { word: "שרברב", en: "Plumber", img: "/words/junior/plumber.webp" },
  { word: "דוב קוטב", en: "Polar Bear", img: "/words/junior/polar_bear.webp" },
  { word: "פופקורן", en: "Popcorn", img: "/words/junior/popcorn.webp" },
  { word: "ארטיק", en: "Popsicle", img: "/words/junior/popsicle.webp" },
  { word: "מדפסת", en: "Printer", img: "/words/junior/printer.webp" },
  { word: "קשת בענן", en: "Rainbow", img: "/words/junior/rainbow.webp" },
  { word: "קרנף", en: "Rhinoceros", img: "/words/junior/rhinoceros.webp" },
  { word: "קרנף קטן", en: "Rhino", img: "/words/junior/rhino.webp" },
  { word: "טבעות", en: "Ring", img: "/words/junior/ring.webp" },
  { word: "עוף צלוי", en: "Roast Chicken", img: "/words/junior/roast_chicken.webp" },
  { word: "חללית", en: "Rocket", img: "/words/junior/rocket.webp" },
  { word: "גלגיליות", en: "Rollerblades", img: "/words/junior/rollerblades.webp" },
  
  { word: "סלט", en: "Salad", img: "/words/junior/salad.webp" },
  { word: "קורקינט", en: "Scooter", img: "/words/junior/scooter.webp" },
  { word: "עקרב", en: "Scorpion", img: "/words/junior/scorpion.webp" },
  { word: "פסל", en: "Sculptor", img: "/words/junior/sculptor.webp" },
  { word: "ים", en: "Sea", img: "/words/junior/sea.webp" },
  
  { word: "כריש", en: "Shark", img: "/words/junior/shark.webp" },
  { word: "ספינה", en: "Ship", img: "/words/junior/ship.webp" },
  { word: "זמר", en: "Singer", img: "/words/junior/singer.webp" },
  { word: "כיור", en: "Sink", img: "/words/junior/sink.webp" },
  { word: "סקי", en: "Skiing", img: "/words/junior/skiing.webp" },
  { word: "עצלן", en: "Sloth", img: "/words/junior/sloth.webp" },
  { word: "טלפון חכם", en: "Smartphone", img: "/words/junior/smartphone.webp" },
  { word: "נחש", en: "Snake", img: "/words/junior/snake.webp" },
  { word: "כדורגל", en: "Soccer", img: "/words/junior/soccer.webp" },
  { word: "מרק", en: "Soup", img: "/words/junior/soup.webp" },
  { word: "משגר רקטות", en: "Space Shuttle", img: "/words/junior/space_shuttle.webp" },
  { word: "חללית", en: "Spaceship", img: "/words/junior/spaceship.webp" },
  { word: "סנאי", en: "Squirrel", img: "/words/junior/squirrel.webp" },
  { word: "אצטדיון", en: "Stadium", img: "/words/junior/stadium.webp" },
  { word: "חותמת", en: "Stamp", img: "/words/junior/stamp.webp" },
  { word: "מהדק", en: "Stapler", img: "/words/junior/stapler.webp" },
  { word: "כוכב ים", en: "Starfish", img: "/words/junior/starfish.webp" },
  { word: "סטייק", en: "Steak", img: "/words/junior/steak.webp" },
  { word: "מזוודה", en: "Suitcase", img: "/words/junior/suitcase.webp" },
  { word: "גלישת גלים", en: "Surfing", img: "/words/junior/surfing.webp" },
  { word: "סושי", en: "Sushi", img: "/words/junior/sushi.webp" },
  { word: "ברבור", en: "Swan", img: "/words/junior/swan.webp" },
  { word: "טנק", en: "Tank", img: "/words/junior/tank.webp" },
  { word: "סרט מידה", en: "Tape Measure", img: "/words/junior/tape_measure.webp" },
  { word: "תה", en: "Tea", img: "/words/junior/tea.webp" },
  { word: "טניס", en: "Tennis", img: "/words/junior/tennis.webp" },
  { word: "אוהל", en: "Tent", img: "/words/junior/tent.webp" },
  { word: "מבחנה", en: "Test Tube", img: "/words/junior/test_tube.webp" },
  { word: "טוסטר", en: "Toaster", img: "/words/junior/toaster.webp" },
  { word: "אסלה", en: "Toilet", img: "/words/junior/toilet.webp" },
  { word: "מברשת שיניים", en: "Toothbrush", img: "/words/junior/toothbrush.webp" },
  { word: "טורנדו", en: "Tornado", img: "/words/junior/tornado.webp" },
  { word: "טרקטור", en: "Tractor", img: "/words/junior/tractor.webp" },
  { word: "רכבת", en: "Train", img: "/words/junior/train.webp" },
  { word: "פח אשפה", en: "Trash Can", img: "/words/junior/trash_can.webp" },
  { word: "גביע", en: "Trophy", img: "/words/junior/trophy.webp" },
  { word: "חצוצרה", en: "Trumpet", img: "/words/junior/trumpet.webp" },
  { word: "צב", en: "Turtle", img: "/words/junior/turtle.webp" },
  { word: "מכונת כתיבה", en: "Typewriter", img: "/words/junior/typewriter.webp" },
  { word: "מטריה", en: "Umbrella", img: "/words/junior/umbrella.webp" },
  { word: "חד קרן", en: "Unicorn", img: "/words/junior/unicorn.webp" },
  { word: "שואב אבק", en: "Vacuum Cleaner", img: "/words/junior/vacuum_cleaner.webp" },
  { word: "וטרינר", en: "Veterinarian", img: "/words/junior/veterinarian.webp" },
  { word: "כינור", en: "Violin", img: "/words/junior/violin.webp" },
  { word: "הר געש", en: "Volcano", img: "/words/junior/volcano.webp" },
  { word: "כדורעף", en: "Volleyball", img: "/words/junior/volleyball.webp" },
  { word: "וופל", en: "Waffle", img: "/words/junior/waffle.webp" },
  { word: "ארנק", en: "Wallet", img: "/words/junior/wallet.webp" },
  { word: "מפל", en: "Waterfall", img: "/words/junior/waterfall.webp" },
  { word: "לווייתן", en: "Whale", img: "/words/junior/whale.webp" },
  { word: "משרוקית", en: "Whistle", img: "/words/junior/whistle.webp" },
  { word: "טחנת רוח", en: "Windmill", img: "/words/junior/windmill.webp" },
  { word: "זאב", en: "Wolf", img: "/words/junior/wolf.webp" },
  { word: "שעון יד", en: "Wristwatch", img: "/words/junior/wristwatch.webp" },
  { word: "יוגה", en: "Yoga", img: "/words/junior/yoga.webp" },
  
  
  

  // --- המילים החדשות (43 מילים קודמות) ---
  { word: "קריקט", en: "Cricket", img: "/words/junior/cricket.webp" },
  { word: "בונה", en: "Beaver", img: "/words/junior/beaver.webp" },
  { word: "בואש", en: "Skunk", img: "/words/junior/skunk.webp" },
  { word: "איגואנה", en: "Iguana", img: "/words/junior/iguana.webp" },
  { word: "עגל", en: "Calf", img: "/words/junior/calf.webp" },
  { word: "חתלתול", en: "Kitten", img: "/words/junior/kitten.webp" },
  { word: "כלבלב", en: "Puppy", img: "/words/junior/puppy.webp" },
  { word: "סייח", en: "Foal", img: "/words/junior/foal.webp" },
  { word: "חסידה", en: "Stork", img: "/words/junior/stork.webp" },
  { word: "עורב", en: "Crow", img: "/words/junior/crow.webp" },
  { word: "ברוקולי", en: "Broccoli", img: "/words/junior/broccoli.webp" },
  { word: "שום", en: "Garlic", img: "/words/junior/garlic.webp" },
  { word: "אפונה", en: "Peas", img: "/words/junior/peas.webp" },
  { word: "כרוב", en: "Cabbage", img: "/words/junior/cabbage.webp" },
  { word: "תרד", en: "Spinach", img: "/words/junior/spinach.webp" },
  { word: "אספרגוס", en: "Asparagus", img: "/words/junior/asparagus.webp" },
  { word: "אוכמניות", en: "Blueberry", img: "/words/junior/blueberry.webp" },
  { word: "פטל שחור", en: "Blackberry", img: "/words/junior/blackberry.webp" },
  { word: "תאנה", en: "Fig", img: "/words/junior/fig.webp" },
  { word: "בייגלה", en: "Pretzel", img: "/words/junior/pretzel.webp" },
  { word: "חביתה", en: "Omelet", img: "/words/junior/omelet.webp" },
  { word: "טוסט", en: "Toast", img: "/words/junior/toast.webp" },
  { word: "עט", en: "Pen", img: "/words/junior/pen.webp" },
  { word: "ביצת עין", en: "Eye Egg", img: "/words/junior/eye_egg.webp" },
  { word: "קנקן תה", en: "Teapot", img: "/words/junior/teapot.webp" },
  { word: "מאפרה", en: "Ashtray", img: "/words/junior/ashtray.webp" },
  { word: "צנצנת ממתקים", en: "Candy Jar", img: "/words/junior/candy_jar.webp" },
  { word: "מייבש שיער", en: "Dryer", img: "/words/junior/dryer.webp" },
  { word: "קולב", en: "Hanger", img: "/words/junior/hanger.webp" },
  { word: "מגירות", en: "Drawers", img: "/words/junior/drawers.webp" },
  { word: "ברז", en: "Faucet", img: "/words/junior/faucet.webp" },
  { word: "וילון", en: "Curtain", img: "/words/junior/curtain.webp" },
  { word: "אגרטל", en: "Vase", img: "/words/junior/vase.webp" },
  { word: "מסגרת תמונה", en: "Picture Frame", img: "/words/junior/picture_frame.webp" },
  { word: "ציפורניים", en: "Nail", img: "/words/junior/nails.webp" },
  { word: "בורג", en: "Screw", img: "/words/junior/screw.webp" },
  { word: "דבק", en: "Glue", img: "/words/junior/glue.webp" },
  { word: "גלגל ענק", en: "Ferris Wheel", img: "/words/junior/ferris_wheel.webp" },
  { word: "תכשיטים", en: "Jewelry", img: "/words/junior/jewelry.webp" },
  { word: "פאזל", en: "Puzzle", img: "/words/junior/puzzle.webp" },
  { word: "פלפל", en: "Pepper", img: "/words/junior/pepper.webp" },
  { word: "יאכטה", en: "Yacht", img: "/words/junior/yacht.webp" },
  { word: "כביש", en: "Road", img: "/words/junior/road.webp" },

  // --- המילים החדשות (עברו לתיקייה הראשית של junior) ---
  { word: "שינה", en: "Sleep", img: "/words/junior/sleep.webp" },
  { word: "מיטה", en: "Bed", img: "/words/junior/bed.webp" },
  { word: "שולחן פיקניק", en: "Picnic Bench", img: "/words/junior/picnic_bench.webp" },
  { word: "חלון ראווה", en: "Showcase", img: "/words/junior/showcase.webp" },
  { word: "אח", en: "Fireplace", img: "/words/junior/fire_place.webp" },
  { word: "מכונת כביסה", en: "Washing Machine", img: "/words/junior/laundry_machine.webp" },
  { word: "מטבח", en: "Kitchen", img: "/words/junior/Kitchen.webp" },
  { word: "קוביה הונגרית", en: "Hungarian Cube", img: "/words/junior/Hungarian_cube.webp" },
  { word: "ערסל", en: "Hammock", img: "/words/junior/hammock.webp" },
  { word: "שולחן ביליארד", en: "Pool Table", img: "/words/junior/Pool_table.webp" },
  { word: "מצעים", en: "Bedding", img: "/words/junior/bedding.webp" },
  { word: "מחשב נייד", en: "Laptop", img: "/words/junior/Laptop.webp" },
  { word: "ספסל", en: "Bench", img: "/words/junior/bench.webp" },
  { word: "חדר ארונות", en: "Walk-in Closet", img: "/words/junior/closet_room.webp" },
  { word: "שרשרת", en: "Necklace", img: "/words/junior/Necklace.webp" },
  { word: "טבעת יהלום", en: "Diamond Ring", img: "/words/junior/diamond_ring.webp" },
  { word: "תליון", en: "Pendant", img: "/words/junior/pendant.webp" },
  { word: "צמיד", en: "Bracelet", img: "/words/junior/bracelet.webp" },
  { word: "שעון חכם", en: "Smart Watch", img: "/words/junior/smart_watch.webp" },
  { word: "גומיות", en: "Rubber Bands", img: "/words/junior/rubber_bands.webp" },
  { word: "סיכות ראש", en: "Hair Pins", img: "/words/junior/hair_pins.webp" },
  { word: "מניפה", en: "Fan", img: "/words/junior/fan.webp" },
  { word: "כובע צמר", en: "Wool Hat", img: "/words/junior/wool_hat.webp" },
  { word: "כפפות", en: "Gloves", img: "/words/junior/gloves.webp" },
  { word: "רקדנית", en: "Dancer", img: "/words/junior/dancer.webp" },
  { word: "מפצח אגוזים", en: "Nutcracker", img: "/words/junior/nutcracker.webp" },
  { word: "טבח", en: "Cook", img: "/words/junior/cook.webp" },
  { word: "קיר טיפוס", en: "Climbing Wall", img: "/words/junior/climbing_wall.webp" },
  { word: "סנדלים", en: "Sandals", img: "/words/junior/sandals.webp" },
  { word: "גלשן", en: "Surfboard", img: "/words/junior/surfboard.webp" },
  { word: "חולצת טי", en: "T-Shirt", img: "/words/junior/T_shirt.webp" },
  { word: "כפפת שוער", en: "Goalkeeper Glove", img: "/words/junior/goalkeeper_glove.webp" }
];