// app/lib/words/kids.ts
import { WordItem } from "../../game.config";

export const KIDS_WORDS: WordItem[] = [
  // --- המילים המקוריות (105 מילים) ---
  { word: "מַזְגָן", en: "Air Conditioner", img: "/words/kids/air_conditioner.webp" },
  { word: "נְמָלָה", en: "Ant", img: "/words/kids/ant.webp" },
  { word: "תַּפּוּחַ", en: "Apple", img: "/words/kids/apple.webp" },
  { word: "אַסְטְרוֹנָאוּט", en: "Astronaut", img: "/words/kids/astronaut.webp" },
  { word: "בָּנָנָה", en: "Banana", img: "/words/kids/banana.webp" },
  { word: "כַּדּוּרֶסֶל", en: "Basketball", img: "/words/kids/basketball.webp" },
  { word: "עֲטַלֵּף", en: "Bat", img: "/words/kids/bat.webp" },
  { word: "סוֹלְלָה", en: "Battery", img: "/words/kids/battery.webp" },
  { word: "דְּבוֹרָה", en: "Bee", img: "/words/kids/bee.webp" },
  { word: "אוֹפַנַּיִם", en: "Bicycle", img: "/words/kids/bicycle.webp" },
  { word: "מַגְפַיִם", en: "Boots", img: "/words/kids/boots.webp" },
  { word: "לֶחֶם", en: "Bread", img: "/words/kids/bread.webp" },
  { word: "דַּחְפּוֹר", en: "Bulldozer", img: "/words/kids/bulldozer.webp" },
  { word: "אוֹטוֹבּוּס", en: "Bus", img: "/words/kids/bus.webp" },
  { word: "פַּרְפַּר", en: "Butterfly", img: "/words/kids/butterfly.webp" },
  { word: "מַחְשֵׁבוֹן", en: "Calculator", img: "/words/kids/calculator.webp" },
  { word: "גָּמָל", en: "Camel", img: "/words/kids/camel.webp" },
  { word: "מַצְלֵמָה", en: "Camera", img: "/words/kids/camera.webp" },
  { word: "נֵר", en: "Candle", img: "/words/kids/candle.webp" },
  { word: "מְכוֹנִית", en: "Car", img: "/words/kids/car.webp" },
  { word: "חָתוּל", en: "Cat", img: "/words/kids/cat.webp" },
  { word: "צֵ'לוֹ", en: "Cello", img: "/words/kids/cello.webp" },
  { word: "זִקִּית", en: "Chameleon", img: "/words/kids/chameleon.webp" },
  { word: "בַּרְדְּלָס", en: "Cheetah", img: "/words/kids/cheetah.webp" },
  { word: "שַׁחְמָט", en: "Chess", img: "/words/kids/chess.webp" },
  { word: "אֶפְרוֹחַ", en: "Chick", img: "/words/kids/chick.webp" },
  { word: "עָנָן", en: "Cloud", img: "/words/kids/cloud.webp" },
  { word: "תִּירָס", en: "Corn", img: "/words/kids/corn.webp" },
  { word: "פָּרָה", en: "Cow", img: "/words/kids/cow.webp" },
  { word: "סַרְטָן", en: "Crab", img: "/words/kids/crab.webp" },
  { word: "מָנוֹף", en: "Crane", img: "/words/kids/crane.webp" },
  { word: "מְלָפְפוֹן", en: "Cucumber", img: "/words/kids/cucumber.webp" },
  { word: "כּוֹס", en: "Cup", img: "/words/kids/cup.webp" },
  { word: "כֶּלֶב", en: "Dog", img: "/words/kids/dog.webp" },
  { word: "דֶּלֶת", en: "Door", img: "/words/kids/door.webp" },
  { word: "מַקְדֵּחָה", en: "Drill", img: "/words/kids/drill.webp" },
  { word: "תֻּפִּים", en: "Drums", img: "/words/kids/drums.webp" },
  { word: "בַּרְוָז", en: "Duck", img: "/words/kids/duck.webp" },
  { word: "פִּיל", en: "Elephant", img: "/words/kids/elephant.webp" },
  { word: "כַּבַּאי", en: "Firefighter", img: "/words/kids/firefighter.webp" },
  { word: "דָּג", en: "Fish", img: "/words/kids/fish.webp" },
  { word: "פֶּרַח", en: "Flower", img: "/words/kids/flower.webp" },
  { word: "חָלִיל", en: "Flute", img: "/words/kids/flute.webp" },
  { word: "שׁוּעָל", en: "Fox", img: "/words/kids/fox.webp" },
  { word: "מְקָרֵר", en: "Fridge", img: "/words/kids/fridge.webp" },
  { word: "צְפַרְדֵּעַ", en: "Frog", img: "/words/kids/frog.webp" },
  { word: "מַתָּנָה", en: "Gift", img: "/words/kids/gift.webp" },
  { word: "גִּ'ירָפָה", en: "Giraffe", img: "/words/kids/giraffe.webp" },
  { word: "עֲנָבִים", en: "Grapes", img: "/words/kids/grapes.webp" },
  { word: "דֶּשֶׁא", en: "Grass", img: "/words/kids/grass.webp" },
  { word: "יָד", en: "Hand", img: "/words/kids/hand.webp" },
  { word: "כּוֹבַע", en: "Hat", img: "/words/kids/hat.webp" },
  { word: "אוֹזְנִיּוֹת", en: "Headphones", img: "/words/kids/headphones.webp" },
  { word: "קִפּוֹד", en: "Hedgehog", img: "/words/kids/hedgehog.webp" },
  { word: "מַסּוֹק", en: "Helicopter", img: "/words/kids/helicopter.webp" },
  { word: "הִיפּוֹפּוֹטָם", en: "Hippopotamus", img: "/words/kids/hippopotamus.webp" },
  { word: "סוּס", en: "Horse", img: "/words/kids/horse.webp" },
  { word: "נַקְנִיקִיָּה", en: "Hotdog", img: "/words/kids/hotdog.webp" },
  { word: "גְּלִידָה", en: "Ice Cream", img: "/words/kids/ice_cream.webp" },
  { word: "מַפְתֵּחַ", en: "Key", img: "/words/kids/key.webp" },
  { word: "סֻלָּם", en: "Ladder", img: "/words/kids/ladder.webp" },
  { word: "חִפּוּשִׁית", en: "Ladybug", img: "/words/kids/ladybug.webp" },
  { word: "עָלֶה", en: "Leaf", img: "/words/kids/leaf.webp" },
  { word: "אַרְיֵה", en: "Lion", img: "/words/kids/lion.webp" },
  { word: "זְכוּכִית מַגְדֶּלֶת", en: "Magnifying Glass", img: "/words/kids/magnifying_glass.webp" },
  { word: "מַדַּלְיָה", en: "Medal", img: "/words/kids/medal.webp" },
  { word: "חָלָב", en: "Milk", img: "/words/kids/milk.webp" },
  { word: "קוֹף", en: "Monkey", img: "/words/kids/monkey.webp" },
  { word: "יָרֵחַ", en: "Moon", img: "/words/kids/moon.webp" },
  { word: "אוֹפַנּוֹעַ", en: "Motorcycle", img: "/words/kids/motorcycle.webp" },
  { word: "פִּטְרִיָּה", en: "Mushroom", img: "/words/kids/mushroom.webp" },
  { word: "תַּפּוּז", en: "Orange", img: "/words/kids/orange.webp" },
  { word: "יַנְשׁוּף", en: "Owl", img: "/words/kids/owl.webp" },
  { word: "תּוּכִּי", en: "Parrot", img: "/words/kids/parrot.webp" },
  { word: "טַוָּס", en: "Peacock", img: "/words/kids/peacock.webp" },
  { word: "אַגָּס", en: "Pear", img: "/words/kids/pear.webp" },
  { word: "פִּינְגְּוִין", en: "Penguin", img: "/words/kids/penguin.webp" },
  { word: "פִּלְפֵּל", en: "Pepper", img: "/words/kids/pepper.webp" },
  { word: "אֲנָנָס", en: "Pineapple", img: "/words/kids/pineapple.webp" },
  { word: "פִּיצָה", en: "Pizza", img: "/words/kids/pizza.webp" },
  { word: "פּוֹפְּקוֹרְן", en: "Popcorn", img: "/words/kids/popcorn.webp" },
  { word: "אַרְנָב", en: "Rabbit", img: "/words/kids/rabbit.webp" },
  { word: "קַרְנַף", en: "Rhino", img: "/words/kids/rhino.webp" },
  { word: "טַבַּעַת", en: "Ring", img: "/words/kids/ring.webp" },
  { word: "קוֹרְקִינֶט", en: "Scooter", img: "/words/kids/scooter.webp" },
  { word: "עַקְרָב", en: "Scorpion", img: "/words/kids/scorpion.webp" },
  { word: "כִּבְשָׂה", en: "Sheep", img: "/words/kids/sheep.webp" },
  { word: "נַעֲלַיִם", en: "Shoes", img: "/words/kids/shoes.webp" },
  { word: "חִלָּזוֹן", en: "Snail", img: "/words/kids/snail.webp" },
  { word: "נָחָשׁ", en: "Snake", img: "/words/kids/snake.webp" },
  { word: "כַּדּוּרֶגֶל", en: "Soccer", img: "/words/kids/soccer.webp" },
  { word: "סוּשִׁי", en: "Sushi", img: "/words/kids/sushi.webp" },
  { word: "טַנְק", en: "Tank", img: "/words/kids/tank.webp" },
  { word: "אוֹהֶל", en: "Tent", img: "/words/kids/tent.webp" },
  { word: "עַגְבָנִיָּה", en: "Tomato", img: "/words/kids/tomato.webp" },
  { word: "מִבְרֶשֶׁת שִׁנַּיִם", en: "Toothbrush", img: "/words/kids/toothbrush.webp" },
  { word: "טְרַקְטוֹר", en: "Tractor", img: "/words/kids/tractor.webp" },
  { word: "רַכֶּבֶת", en: "Train", img: "/words/kids/train.webp" },
  { word: "עֵץ", en: "Tree", img: "/words/kids/tree.webp" },
  { word: "גָּבִיעַ", en: "Trophy", img: "/words/kids/trophy.webp" },
  { word: "מַשָּׂאִית", en: "Truck", img: "/words/kids/truck.webp" },
  { word: "צָב", en: "Turtle", img: "/words/kids/turtle.webp" },
  { word: "שׁוֹאֵב אָבָק", en: "Vacuum Cleaner", img: "/words/kids/vacuum_cleaner.webp" },
  { word: "מַשְׁרוֹקִית", en: "Whistle", img: "/words/kids/whistle.webp" },
  { word: "זֶבְּרָה", en: "Zebra", img: "/words/kids/zebra.webp" },

  // --- המילים החדשות (65 מילים) ---
  { word: "טִירָה", en: "Castle", img: "/words/kids/castle.webp" },
  { word: "גֶּשֶׁר", en: "Bridge", img: "/words/kids/bridge.webp" },
  { word: "דֶּגֶל", en: "Flag", img: "/words/kids/flag.webp" },
  { word: "פָּזֶל", en: "Puzzle", img: "/words/kids/puzzle.webp" },
  { word: "כַּבָּאִית", en: "Fire Truck", img: "/words/kids/fire_truck.webp" },
  { word: "צַולְלָן", en: "Diver", img: "/words/kids/diver.webp" },
  { word: "סְפִינָה", en: "Ship", img: "/words/kids/ship.webp" },
  { word: "סִירָה", en: "Boat", img: "/words/kids/boat.webp" },
  { word: "מִזְוָדָה", en: "Suitcase", img: "/words/kids/suitcase.webp" },
  { word: "חֲגוֹרָה", en: "Belt", img: "/words/kids/belt.webp" },
  { word: "יַלְדָּה", en: "Girl", img: "/words/kids/girl.webp" },
  { word: "גבר", en: "Man", img: "/words/kids/man.webp" },
  { word: "כַּדּוּר הָאָרֶץ", en: "Earth", img: "/words/kids/earth.webp" },
  { word: "יַעַר", en: "Forest", img: "/words/kids/forest.webp" },
  { word: "מִדְבָּר", en: "Desert", img: "/words/kids/desert.webp" },
  { word: "צֶדֶף", en: "Shell", img: "/words/kids/shell.webp" },
  { word: "חוֹף", en: "Beach", img: "/words/kids/beach.webp" },
  { word: "הַר", en: "Mountain", img: "/words/kids/mountain.webp" },
  { word: "אֵשׁ", en: "Fire", img: "/words/kids/fire.webp" },
  { word: "שֶׁלֶג", en: "Snow", img: "/words/kids/snow.webp" },
  { word: "עֲנָנִים", en: "Clouds", img: "/words/kids/clouds.webp" },
  { word: "קֶשֶׁת בֶּעָנָן", en: "Rainbow", img: "/words/kids/rainbow.webp" },
  { word: "חותמת", en: "Stamp", img: "/words/kids/stamp.webp" },
  { word: "שָׁטִיחַ", en: "Rug", img: "/words/kids/rug.webp" },
  { word: "סַפָּה", en: "Sofa", img: "/words/kids/sofa.webp" },
  { word: "סְפָרִים", en: "Books", img: "/words/kids/books.webp" },
  { word: "אֵת חֲפִירָה", en: "Shovel", img: "/words/kids/shovel.webp" },
  { word: "פַּחִית", en: "Can", img: "/words/kids/can.webp" },
  { word: "בַּקְבּוּק", en: "Bottle", img: "/words/kids/bottle.webp" },
  { word: "תיק", en: "Bag", img: "/words/kids/bag.webp" },
  { word: "מִיקְרוֹגַל", en: "Microwave", img: "/words/kids/microwave.webp" },
  { word: "נוּרָה", en: "Bulb", img: "/words/kids/bulb.webp" },
  { word: "מִקְלַחַת", en: "Shower", img: "/words/kids/shower.webp" },
  { word: "שֵׁיְרוּתִים", en: "Toilet", img: "/words/kids/toilet.webp" },
  { word: "כִּיּוֹר", en: "Sink", img: "/words/kids/sink.webp" },
  { word: "פַּטִּישׁ", en: "Hammer", img: "/words/kids/hammer.webp" },
  { word: "פְּסַנְתֵּר", en: "Piano", img: "/words/kids/piano.webp" },
  { word: "שָׁעוֹן", en: "Clock", img: "/words/kids/clock.webp" },
  { word: "מְנוֹרָה", en: "Lamp", img: "/words/kids/lamp.webp" },
  { word: "קָפֶה", en: "Coffee", img: "/words/kids/coffee.webp" },
  { word: "בּוֹטֶן", en: "Peanut", img: "/words/kids/peanut.webp" },
  { word: "קוֹקוֹס", en: "Coconut", img: "/words/kids/coconut.webp" },
  { word: "מָרָק", en: "Soup", img: "/words/kids/soup.webp" },
  { word: "ארטיק", en: "Lollipop", img: "/words/kids/lollipop.webp" },
  { word: "עוּגָה", en: "Cake", img: "/words/kids/cake.webp" },
  { word: "עוּגִיּוֹת", en: "Cookies", img: "/words/kids/cookies.webp" },
  { word: "הַמְבּוּרְגֶּר", en: "Burger", img: "/words/kids/burger.webp" },
  { word: "דְּבַשׁ", en: "Honey", img: "/words/kids/honey.webp" },
  { word: "בֵּיצָה", en: "Egg", img: "/words/kids/egg.webp" },
  { word: "אָבוֹקָדוֹ", en: "Avocado", img: "/words/kids/avocado.webp" },
  { word: "קִיוִוי", en: "Kiwi", img: "/words/kids/kiwi.webp" },
  { word: "אֲפַרְסֵק", en: "Peach", img: "/words/kids/peach.webp" },
  { word: "תַּרְנְגוֹל", en: "Rooster", img: "/words/kids/rooster.webp" },
  { word: "יוֹנָה", en: "Pigeon", img: "/words/kids/pigeon.webp" },
  { word: "אֲווז", en: "Goose", img: "/words/kids/goose.webp" },
  { word: "יָעֵן", en: "Ostrich", img: "/words/kids/ostrich.webp" },
  { word: "צְבִי", en: "Deer", img: "/words/kids/deer.webp" },
  { word: "דֹּב", en: "Bear", img: "/words/kids/bear.webp" },
  { word: "בַּרְבּוּר", en: "Swan", img: "/words/kids/swan.webp" },
  { word: "פְלָמִינְגּוֹ", en: "Flamingo", img: "/words/kids/flamingo.webp" },
  { word: "סְנָאי", en: "Squirrel", img: "/words/kids/squirrel.webp" },
  { word: "עֵז", en: "Goat", img: "/words/kids/goat.webp" },
  { word: "בַּרְוָז גּוּמִי", en: "Rubber Duck", img: "/words/kids/rubber_duck.webp" },
  { word: "מְדוּזָה", en: "Jellyfish", img: "/words/kids/jellyfish.webp" },
  { word: "זְאֵב", en: "Wolf", img: "/words/kids/wolf.webp" }
];