import { WordItem } from "../../game.config";

export const TEEN_WORDS: WordItem[] = [
  // --- רגשות ותחושות (1-150) ---
  { word: "געגוע", en: "Longing" }, { word: "קנאה", en: "Jealousy" },
  { word: "תקווה", en: "Hope" }, { word: "אכזבה", en: "Disappointment" },
  { word: "התרגשות", en: "Excitement" }, { word: "ביישנות", en: "Shyness" },
  { word: "ביטחון", en: "Confidence" }, { word: "פחד", en: "Fear" },
  { word: "שמחה", en: "Joy" }, { word: "עצב", en: "Sadness" },
  { word: "כעס", en: "Anger" }, { word: "סקרנות", en: "Curiosity" },
  { word: "עלבון", en: "Insult" }, { word: "גאווה", en: "Pride" },
  { word: "אומץ", en: "Courage" }, { word: "בדידות", en: "Loneliness" },
  { word: "שייכות", en: "Belonging" }, { word: "לחץ", en: "Stress" },
  { word: "שלווה", en: "Serenity" }, { word: "הפתעה", en: "Surprise" },
  { word: "סלידה", en: "Disgust" }, { word: "דאגה", en: "Worry" },
  { word: "הערצה", en: "Admiration" }, { word: "בושה", en: "Shame" },
  { word: "הודיה", en: "Gratitude" }, { word: "בלבול", en: "Confusion" },
  { word: "חרטה", en: "Regret" }, { word: "סיפוק", en: "Satisfaction" },
  { word: "מבוכה", en: "Embarrassment" }, { word: "חשד", en: "Suspicion" },
  { word: "ציפייה", en: "Expectation" }, { word: "נחישות", en: "Determination" },
  { word: "עייפות", en: "Fatigue" }, { word: "שעמום", en: "Boredom" },
  { word: "איפוק", en: "Restraint" }, { word: "הקלה", en: "Relief" },
  { word: "מרדנות", en: "Rebelliousness" }, { word: "קרבה", en: "Closeness" },
  { word: "אימה", en: "Dread" }, { word: "חיבה", en: "Affection" },
  { word: "עוינות", en: "Hostility" }, { word: "שעשוע", en: "Amusement" },
  { word: "זלזול", en: "Contempt" }, { word: "חמלה", en: "Compassion" },
  { word: "ערגה", en: "Yearning" }, { word: "קנאות", en: "Fanaticism" },
  { word: "דחייה", en: "Rejection" }, { word: "היסוס", en: "Hesitation" },
  { word: "ביטחון עצמי", en: "Self-confidence" }, { word: "שנאה", en: "Hatred" },
  { word: "חרדה", en: "Anxiety" }, { word: "היקשרות", en: "Attachment" },
  { word: "סבלנות", en: "Patience" }, { word: "סובלנות", en: "Tolerance" },
  { word: "נחמה", en: "Comfort" }, { word: "ערנות", en: "Alertness" },
  { word: "תשישות", en: "Exhaustion" }, { word: "בהלה", en: "Panic" },
  { word: "נינוחות", en: "Comfort" }, { word: "אושר", en: "Happiness" },
  { word: "תעוזה", en: "Daring" }, { word: "צער", en: "Grief" },
  { word: "פליאה", en: "Wonder" }, { word: "השתאות", en: "Astonishment" },

  // --- ערכים, תכונות ואופי (151-300) ---
  { word: "אחריות", en: "Responsibility" }, { word: "עצמאות", en: "Independence" },
  { word: "נאמנות", en: "Loyalty" }, { word: "חברות", en: "Friendship" },
  { word: "יושר", en: "Honesty" }, { word: "עקשנות", en: "Stubbornness" },
  { word: "חריצות", en: "Diligence" }, { word: "סדר", en: "Order" },
  { word: "משמעת", en: "Discipline" }, { word: "הגינות", en: "Fairness" },
  { word: "צניעות", en: "Modesty" }, { word: "נדיבות", en: "Generosity" },
  { word: "סבלנות", en: "Patience" }, { word: "עזרה", en: "Help" },
  { word: "ויתור", en: "Concession" }, { word: "התמדה", en: "Perseverance" },
  { word: "יצירתיות", en: "Creativity" }, { word: "כישרון", en: "Talent" },
  { word: "חוכמה", en: "Wisdom" }, { word: "תמימות", en: "Innocence" },
  { word: "בגרות", en: "Maturity" }, { word: "רצינות", en: "Seriousness" },
  { word: "זהירות", en: "Caution" }, { word: "נחמדות", en: "Niceness" },
  { word: "פיקחות", en: "Cleverness" }, { word: "חוצפה", en: "Insolence" },
  { word: "נועזות", en: "Boldness" }, { word: "חביבות", en: "Friendliness" },
  { word: "ערמומיות", en: "Cunning" }, { word: "זריזות", en: "Agility" },
  { word: "דייקנות", en: "Punctuality" }, { word: "סלחנות", en: "Forgiveness" },
  { word: "סקרנות", en: "Curiosity" }, { word: "צייתנות", en: "Obedience" },
  { word: "הקרבה", en: "Sacrifice" }, { word: "ענווה", en: "Humility" },
  { word: "מסירות", en: "Dedication" }, { word: "צדק", en: "Justice" },
  { word: "שלום", en: "Peace" }, { word: "חופש", en: "Freedom" },
  { word: "כנות", en: "Sincerity" }, { word: "אדיבות", en: "Politeness" },
  { word: "שחצנות", en: "Arrogance" }, { word: "פחדנות", en: "Cowardice" },
  { word: "קמצנות", en: "Stinginess" }, { word: "פזרנות", en: "Extravagance" },
  { word: "חמדנות", en: "Greed" }, { word: "עדינות", en: "Gentleness" },
  { word: "גבורה", en: "Bravery" }, { word: "יוזמה", en: "Initiative" },
  { word: "מנהיגות", en: "Leadership" }, { word: "אצילות", en: "Nobility" },
  { word: "ביקורתיות", en: "Criticalness" }, { word: "אמינות", en: "Reliability" },

  // --- חברה, יחסים וקבוצה (301-450) ---
  { word: "שותפות", en: "Partnership" }, { word: "תחרות", en: "Competition" },
  { word: "לחץ חברתי", en: "Peer pressure" }, { word: "הנהגה", en: "Leadership" },
  { word: "קהילה", en: "Community" }, { word: "שיתוף פעולה", en: "Cooperation" },
  { word: "התנדבות", en: "Volunteering" }, { word: "תרומה", en: "Contribution" },
  { word: "מעמד", en: "Status" }, { word: "פרסום", en: "Fame" },
  { word: "חרם", en: "Boycott" }, { word: "ריב", en: "Quarrel" },
  { word: "פיוס", en: "Reconciliation" }, { word: "סוד", en: "Secret" },
  { word: "אמון", en: "Trust" }, { word: "בגידה", en: "Betrayal" },
  { word: "נאמנות", en: "Loyalty" }, { word: "ידידות", en: "Friendship" },
  { word: "הערכה", en: "Appreciation" }, { word: "כבוד", en: "Respect" },
  { word: "תמיכה", en: "Support" }, { word: "שיחה", en: "Conversation" },
  { word: "ויכוח", en: "Argument" }, { word: "דיון", en: "Discussion" },
  { word: "הקשבה", en: "Listening" }, { word: "הבנה", en: "Understanding" },
  { word: "מפגש", en: "Meeting" }, { word: "בילוי", en: "Leisure" },
  { word: "מסיבה", en: "Party" }, { word: "נשף", en: "Prom" },
  { word: "הדרכה", en: "Guidance" }, { word: "חניכה", en: "Mentorship" },
  { word: "תנועת נוער", en: "Youth movement" }, { word: "מחנה", en: "Camp" },
  { word: "טיול", en: "Trip" }, { word: "מסורת", en: "Tradition" },
  { word: "חגיגה", en: "Celebration" }, { word: "טקס", en: "Ceremony" },
  { word: "זכות", en: "Right" }, { word: "חובה", en: "Duty" },
  { word: "חוק", en: "Law" }, { word: "כלל", en: "Rule" },
  { word: "עונש", en: "Punishment" }, { word: "פרס", en: "Prize" },
  { word: "ביקורת", en: "Criticism" }, { word: "עידוד", en: "Encouragement" },
  { word: "השפעה", en: "Influence" }, { word: "שייכות", en: "Belonging" },
  { word: "דחייה", en: "Rejection" }, { word: "מקובלות", en: "Popularity" },

  // --- לימודים, ידע ומיומנות (451-600) ---
  { word: "הצלחה", en: "Success" }, { word: "כישלון", en: "Failure" },
  { word: "מבחן", en: "Test" }, { word: "למידה", en: "Learning" },
  { word: "זיכרון", en: "Memory" }, { word: "ריכוז", en: "Concentration" },
  { word: "הבנה", en: "Understanding" }, { word: "חקירה", en: "Investigation" },
  { word: "גילוי", en: "Discovery" }, { word: "המצאה", en: "Invention" },
  { word: "ידע", en: "Knowledge" }, { word: "השכלה", en: "Education" },
  { word: "שיעור", en: "Lesson" }, { word: "תרגול", en: "Practice" },
  { word: "משימה", en: "Task" }, { word: "פרויקט", en: "Project" },
  { word: "הישג", en: "Achievement" }, { word: "שיא", en: "Record" },
  { word: "מצוינות", en: "Excellence" }, { word: "סקרנות", en: "Curiosity" },
  { word: "שאלה", en: "Question" }, { word: "תשובה", en: "Answer" },
  { word: "פתרון", en: "Solution" }, { word: "קושי", en: "Difficulty" },
  { word: "אתגר", en: "Challenge" }, { word: "מאמץ", en: "Effort" },
  { word: "יכולת", en: "Ability" }, { word: "פוטנציאל", en: "Potential" },
  { word: "הזדמנות", en: "Opportunity" }, { word: "כישרון", en: "Talent" },
  { word: "דמיון", en: "Imagination" }, { word: "השראה", en: "Inspiration" },
  { word: "מחשבה", en: "Thought" }, { word: "הגיון", en: "Logic" },
  { word: "הוכחה", en: "Proof" }, { word: "מסקנה", en: "Conclusion" },
  { word: "עובדה", en: "Fact" }, { word: "דעה", en: "Opinion" },
  { word: "השערה", en: "Hypothesis" }, { word: "תאוריה", en: "Theory" },
  { word: "ניסוי", en: "Experiment" }, { word: "תוצאה", en: "Result" },
  { word: "שיפור", en: "Improvement" }, { word: "שינוי", en: "Change" },
  { word: "התקדמות", en: "Progress" }, { word: "יצירה", en: "Creation" },
  { word: "ביטוי", en: "Expression" }, { word: "תקשורת", en: "Communication" },
  { word: "שפה", en: "Language" }, { word: "כתיבה", en: "Writing" },
  { word: "קריאה", en: "Reading" }, { word: "ספרות", en: "Literature" },
  { word: "מדע", en: "Science" }, { word: "אמנות", en: "Art" },
  { word: "מוזיקה", en: "Music" }, { word: "ספורט", en: "Sport" },
  { word: "טכנולוגיה", en: "Technology" }, { word: "מחשב", en: "Computer" },

  // --- מושגים מופשטים, זמן וקיום (601-800) ---
  { word: "זמן", en: "Time" }, { word: "עתיד", en: "Future" },
  { word: "עבר", en: "Past" }, { word: "הווה", en: "Present" },
  { word: "נצח", en: "Eternity" }, { word: "גורל", en: "Fate" },
  { word: "מזל", en: "Luck" }, { word: "חלום", en: "Dream" },
  { word: "מציאות", en: "Reality" }, { word: "אמת", en: "Truth" },
  { word: "שקר", en: "Lie" }, { word: "טעות", en: "Mistake" },
  { word: "מקרה", en: "Coincidence" }, { word: "בחירה", en: "Choice" },
  { word: "חופש", en: "Freedom" }, { word: "זכות", en: "Right" },
  { word: "חובה", en: "Duty" }, { word: "אחריות", en: "Responsibility" },
  { word: "משמעות", en: "Meaning" }, { word: "תכלית", en: "Purpose" },
  { word: "סוד", en: "Secret" }, { word: "תעלומה", en: "Mystery" },
  { word: "קסם", en: "Magic" }, { word: "דמיון", en: "Imagination" },
  { word: "מחשבה", en: "Thought" }, { word: "רעיון", en: "Idea" },
  { word: "כוונה", en: "Intention" }, { word: "מעשה", en: "Action" },
  { word: "תוצאה", en: "Consequence" }, { word: "סיבה", en: "Reason" },
  { word: "השפעה", en: "Influence" }, { word: "כוח", en: "Power" },
  { word: "אנרגיה", en: "Energy" }, { word: "תנועה", en: "Movement" },
  { word: "שינוי", en: "Change" }, { word: "התפתחות", en: "Development" },
  { word: "צמיחה", en: "Growth" }, { word: "התבגרות", en: "Adolescence" },
  { word: "ילדות", en: "Childhood" }, { word: "נעורים", en: "Youth" },
  { word: "חיים", en: "Life" }, { word: "מוות", en: "Death" },
  { word: "עולם", en: "World" }, { word: "יקום", en: "Universe" },
  { word: "חלל", en: "Space" }, { word: "מרחב", en: "Space/Range" },
  { word: "מרחק", en: "Distance" }, { word: "קירבה", en: "Proximity" },
  { word: "כיוון", en: "Direction" }, { word: "קצב", en: "Rhythm/Pace" },
  { word: "צליל", en: "Sound" }, { word: "מראה", en: "Appearance" },
  { word: "ריח", en: "Smell" }, { word: "טעם", en: "Taste" },
  { word: "מגע", en: "Touch" }, { word: "תחושה", en: "Sensation" },
  { word: "זיכרון", en: "Memory" }, { word: "שכחה", en: "Oblivion" },
  { word: "התחלה", en: "Beginning" }, { word: "סוף", en: "End" },
  { word: "אמצע", en: "Middle" }, { word: "שלב", en: "Stage" },
  { word: "תהליך", en: "Process" }, { word: "הזדמנות", en: "Opportunity" },
  { word: "סכנה", en: "Danger" }, { word: "ביטחון", en: "Safety" },

  // --- טבע, סביבה ומרחב (801-900) ---
  { word: "סביבה", en: "Environment" }, { word: "טבע", en: "Nature" },
  { word: "נוף", en: "Landscape" }, { word: "אקלים", en: "Climate" },
  { word: "זיהום", en: "Pollution" }, { word: "מחזור", en: "Recycling" },
  { word: "קיימות", en: "Sustainability" }, { word: "שימור", en: "Conservation" },
  { word: "אנרגיה", en: "Energy" }, { word: "משאבים", en: "Resources" },
  { word: "יצור", en: "Production" }, { word: "צריכה", en: "Consumption" },
  { word: "השפעה", en: "Impact" }, { word: "שינוי", en: "Change" },
  { word: "התחממות", en: "Warming" }, { word: "קרחון", en: "Glacier" },
  { word: "אוקיינוס", en: "Ocean" }, { word: "נהר", en: "River" },
  { word: "הר", en: "Mountain" }, { word: "מדבר", en: "Desert" },
  { word: "יער", en: "Forest" }, { word: "שמיים", en: "Sky" },
  { word: "כוכב", en: "Star" }, { word: "ירח", en: "Moon" },
  { word: "שמש", en: "Sun" }, { word: "גלקסיה", en: "Galaxy" },
  { word: "כוכב לכת", en: "Planet" }, { word: "מערכת השמש", en: "Solar system" },
  { word: "אטמוספירה", en: "Atmosphere" }, { word: "חמצן", en: "Oxygen" },
  { word: "כבידה", en: "Gravity" }, { word: "משיכה", en: "Attraction" },
  { word: "מרחק", en: "Distance" }, { word: "מסע", en: "Journey" },

  // --- פעולות, מצבים ואורח חיים (901-1000) ---
  { word: "בחירה", en: "Choice" }, { word: "החלטה", en: "Decision" },
  { word: "פעולה", en: "Action" }, { word: "תנועה", en: "Movement" },
  { word: "מנוחה", en: "Rest" }, { word: "שינה", en: "Sleep" },
  { word: "עבודה", en: "Work" }, { word: "משחק", en: "Play" },
  { word: "לימודים", en: "Studies" }, { word: "תחביב", en: "Hobby" },
  { word: "פנאי", en: "Leisure" }, { word: "בילוי", en: "Entertainment" },
  { word: "שגרה", en: "Routine" }, { word: "הרגל", en: "Habit" },
  { word: "שינוי", en: "Change" }, { word: "התפתחות", en: "Development" },
  { word: "גדילה", en: "Growth" }, { word: "בריאות", en: "Health" },
  { word: "כושר", en: "Fitness" }, { word: "תזונה", en: "Nutrition" },
  { word: "כלכלה", en: "Economics" }, { word: "כסף", en: "Money" },
  { word: "חיסכון", en: "Savings" }, { word: "קניות", en: "Shopping" },
  { word: "צרכנות", en: "Consumerism" }, { word: "פרסום", en: "Advertising" },
  { word: "תקשורת", en: "Media" }, { word: "רשת", en: "Network" },
  { word: "אינטרנט", en: "Internet" }, { word: "מידע", en: "Information" },
  { word: "פרטיות", en: "Privacy" }, { word: "אבטחה", en: "Security" },
  { word: "חברה", en: "Society" }, { word: "קהילה", en: "Community" },
  { word: "תרבות", en: "Culture" }, { word: "אמנות", en: "Art" },
  { word: "מוזיקה", en: "Music" }, { word: "קולנוע", en: "Cinema" },
  { word: "ספרות", en: "Literature" }, { word: "היסטוריה", en: "History" },
  { word: "מדע", en: "Science" }, { word: "טכנולוגיה", en: "Technology" },
  { word: "תחבורה", en: "Transportation" }, { word: "טיול", en: "Travel" },
  { word: "חופשה", en: "Vacation" }, { word: "חג", en: "Holiday" },
  { word: "מסורת", en: "Tradition" }, { word: "דת", en: "Religion" },
  { word: "אמונה", en: "Belief" }, { word: "ערכים", en: "Values" },
  { word: "מוסר", en: "Ethics" }, { word: "צדק", en: "Justice" },
  { word: "שוויון", en: "Equality" }, { word: "חופש", en: "Freedom" },
  { word: "שלום", en: "Peace" }, { word: "ביטחון", en: "Security" },
  { word: "סדר", en: "Order" }, { word: "חוק", en: "Law" },
  { word: "זכות", en: "Right" }, { word: "חובה", en: "Duty" },
  { word: "אחריות", en: "Responsibility" }, { word: "עצמאות", en: "Independence" },
  { word: "מנהיגות", en: "Leadership" }, { word: "מעורבות", en: "Involvement" },
  { word: "התנדבות", en: "Volunteering" }, { word: "תרומה", en: "Contribution" },
  { word: "עזרה", en: "Help" }, { word: "תמיכה", en: "Support" },
  { word: "חברות", en: "Friendship" }, { word: "אהבה", en: "Love" },
  { word: "משפחה", en: "Family" }, { word: "זהות", en: "Identity" },
  { word: "ביטוי עצמי", en: "Self-expression" }, { word: "יצירתיות", en: "Creativity" },
  { word: "דמיון", en: "Imagination" }, { word: "מחשבה", en: "Thought" },
  { word: "דעה", en: "Opinion" }, { word: "ויכוח", en: "Argument" },
  { word: "דיון", en: "Discussion" }, { word: "הסכמה", en: "Agreement" },
  { word: "פשרה", en: "Compromise" }, { word: "סובלנות", en: "Tolerance" },
  { word: "כבוד", en: "Respect" }, { word: "הגינות", en: "Fairness" },
  { word: "יושר", en: "Honesty" }, { word: "אמינות", en: "Reliability" },
  { word: "נאמנות", en: "Loyalty" }, { word: "אמון", en: "Trust" },
  { word: "סקרנות", en: "Curiosity" }, { word: "למידה", en: "Learning" },
  { word: "התפתחות", en: "Growth" }, { word: "הצלחה", en: "Success" },
  { word: "הישג", en: "Achievement" }, { word: "ניצחון", en: "Victory" },
  { word: "אתגר", en: "Challenge" }, { word: "מאמץ", en: "Effort" },
  { word: "התמדה", en: "Persistence" }, { word: "נחישות", en: "Determination" },
  { word: "אומץ", en: "Courage" }, { word: "תקווה", en: "Hope" },
  { word: "חלום", en: "Dream" }, { word: "עתיד", en: "Future" }
];